-- Generated refs_data code list update script
-- Generated at: 2026-06-24 12:38:27 +0200

-- -------------------------------------------------------------------
-- refs_data.logical_responses
-- -------------------------------------------------------------------

INSERT INTO "refs_data"."logical_responses" AS t ("code", "name_en", "name_fr", "description_en", "description_fr") OVERRIDING SYSTEM VALUE VALUES ('TRUE', 'true', 'Vrai', 'The condition is confirmed to be true based on observed or reported data', 'La condition est confirmée comme vraie sur la base des données observées ou rapportées') ON CONFLICT ("code") DO UPDATE SET "name_en" = EXCLUDED."name_en", "name_fr" = EXCLUDED."name_fr", "description_en" = EXCLUDED."description_en", "description_fr" = EXCLUDED."description_fr" WHERE (t."name_en", t."name_fr", t."description_en", t."description_fr") IS DISTINCT FROM (EXCLUDED."name_en", EXCLUDED."name_fr", EXCLUDED."description_en", EXCLUDED."description_fr");
INSERT INTO "refs_data"."logical_responses" AS t ("code", "name_en", "name_fr", "description_en", "description_fr") OVERRIDING SYSTEM VALUE VALUES ('FALSE', 'false', 'Faux', 'The condition is confirmed to be false based on observed or reported data', 'La condition est confirmée comme fausse sur la base des données observées ou rapportées') ON CONFLICT ("code") DO UPDATE SET "name_en" = EXCLUDED."name_en", "name_fr" = EXCLUDED."name_fr", "description_en" = EXCLUDED."description_en", "description_fr" = EXCLUDED."description_fr" WHERE (t."name_en", t."name_fr", t."description_en", t."description_fr") IS DISTINCT FROM (EXCLUDED."name_en", EXCLUDED."name_fr", EXCLUDED."description_en", EXCLUDED."description_fr");
INSERT INTO "refs_data"."logical_responses" AS t ("code", "name_en", "name_fr", "description_en", "description_fr") OVERRIDING SYSTEM VALUE VALUES ('UNK', 'Unknown', 'Inconnu', 'The information could not be determined or observed at the time of data collection', 'L’information n’a pas pu être déterminée ou observée au moment de la collecte des données') ON CONFLICT ("code") DO UPDATE SET "name_en" = EXCLUDED."name_en", "name_fr" = EXCLUDED."name_fr", "description_en" = EXCLUDED."description_en", "description_fr" = EXCLUDED."description_fr" WHERE (t."name_en", t."name_fr", t."description_en", t."description_fr") IS DISTINCT FROM (EXCLUDED."name_en", EXCLUDED."name_fr", EXCLUDED."description_en", EXCLUDED."description_fr");
INSERT INTO "refs_data"."logical_responses" AS t ("code", "name_en", "name_fr", "description_en", "description_fr") OVERRIDING SYSTEM VALUE VALUES ('NAV', 'Not available', 'Non disponible', 'The information was not collected', 'L’information n’a pas été collectée') ON CONFLICT ("code") DO UPDATE SET "name_en" = EXCLUDED."name_en", "name_fr" = EXCLUDED."name_fr", "description_en" = EXCLUDED."description_en", "description_fr" = EXCLUDED."description_fr" WHERE (t."name_en", t."name_fr", t."description_en", t."description_fr") IS DISTINCT FROM (EXCLUDED."name_en", EXCLUDED."name_fr", EXCLUDED."description_en", EXCLUDED."description_fr");
INSERT INTO "refs_data"."logical_responses" AS t ("code", "name_en", "name_fr", "description_en", "description_fr") OVERRIDING SYSTEM VALUE VALUES ('NAP', 'Not applicable', 'Sans objet', 'The variable does not apply to the specific observation or context', 'La variable ne s’applique pas à l’observation ou au contexte considéré') ON CONFLICT ("code") DO UPDATE SET "name_en" = EXCLUDED."name_en", "name_fr" = EXCLUDED."name_fr", "description_en" = EXCLUDED."description_en", "description_fr" = EXCLUDED."description_fr" WHERE (t."name_en", t."name_fr", t."description_en", t."description_fr") IS DISTINCT FROM (EXCLUDED."name_en", EXCLUDED."name_fr", EXCLUDED."description_en", EXCLUDED."description_fr");


