DELETE FROM ros_common.observer where TRUE;
DELETE FROM ros_common.contact_role where TRUE;
DELETE FROM ros_common.contact where TRUE;
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (1, 'MARTIN-BAILET VICTOR', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(1,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(1,'IOTCROS0161');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (2, 'FILIPPI THEO', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(2,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(2,'IOTCROS0084');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (3, 'BODIN NATHALIE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(3,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(3,'IOTCROS0026');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (4, 'ROMANOV EVGENY', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(4,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(4,'IOTCROS0213');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (5, 'SHARP ALAN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(5,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(5,'IOTCROS0221');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (6, 'BERTRAND GEOFFREY', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(6,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(6,'IOTCROS0022');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (7, 'CARO EMMANUEL', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(7,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(7,'IOTCROS0037');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (8, 'POIROUT THOMAS', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(8,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(8,'IOTCROS0190');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (9, 'BRIAND PASCAL', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(9,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(9,'IOTCROS0032');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (10, 'DANIC FABRICE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(10,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(10,'IOTCROS0067');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (11, 'FASSEUR LUDOVIC', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(11,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(11,'IOTCROS0083');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (12, 'MILCENT ANTOINE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(12,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(12,'IOTCROS0166');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (13, 'LAUTROUX STEPHANE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(13,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(13,'IOTCROS0129');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (14, 'MILLAU FREDERIC', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(14,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(14,'IOTCROS0167');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (15, 'DESHAYES MATHIEU', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(15,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(15,'IOTCROS0073');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (16, 'LECOSSEC YANN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(16,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(16,'IOTCROS0147');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (17, 'ROUSSEAU JONATHAN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(17,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(17,'IOTCROS0214');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (18, 'LE PAPE FRED', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(18,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(18,'IOTCROS0142');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (19, 'HODENT TIMOTHEE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(19,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(19,'IOTCROS0103');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (20, 'VASTEL ALICE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(20,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(20,'IOTCROS0241');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (21, 'LE BOURDONNEC PIERRE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(21,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(21,'IOTCROS0131');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (22, 'POPOWICZ THIERRY', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(22,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(22,'IOTCROS0192');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (23, 'FRIGOUT DANIEL', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(23,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(23,'IOTCROS0086');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (24, 'RAFFESTIN PATRICE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(24,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(24,'IOTCROS0200');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (25, 'AUBRAS NATANIEL', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(25,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(25,'IOTCROS0012');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (26, 'TECHER ELPHAGE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(26,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(26,'IOTCROS1001');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (27, 'LE FOULGOC LOIC', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(27,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(27,'IOTCROS0135');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (28, 'LE SAINT MICHEL', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(28,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(28,'IOTCROS0143');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (29, 'BERTHIER PHILIPPE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(29,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(29,'IOTCROS0021');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (30, 'MOUTAL FREDERIC', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(30,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(30,'IOTCROS0174');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (31, 'BENGALA JOSE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(31,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(31,'IOTCROS0020');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (32, 'DIJOUX ROBERT', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(32,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(32,'IOTCROS0075');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (33, 'CHICHERY MICHEL', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(33,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(33,'IOTCROS0054');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (34, 'BASILE WILFRIED', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(34,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(34,'IOTCROS0016');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (35, 'SLIMHANE KEMAT', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(35,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(35,'IOTCROS0997');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (36, 'TATIBOUET JEAN-MARC', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(36,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(36,'IOTCROS0228');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (37, 'AOUSTIN DIDIER', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(37,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(37,'IOTCROS0011');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (38, 'OUILLON BRUNO', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(38,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(38,'IOTCROS0181');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (39, 'MUSSARD FABRICE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(39,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(39,'IOTCROS0175');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (40, 'PAYET FREDERIC', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(40,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(40,'IOTCROS0183');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (41, 'VINCENT ANTHONY', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(41,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(41,'IOTCROS0245');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (42, 'CHEVALLIER ADRIEN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(42,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(42,'IOTCROS0053');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (43, 'FAIVRE CHRISTY', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(43,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(43,'IOTCROS0082');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (44, 'LEBIAN RUDDY', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(44,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(44,'IOTCROS0145');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (45, 'HERVAGAULT ERIC', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(45,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(45,'IOTCROS0100');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (46, 'VERGOZ JEAN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(46,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(46,'IOTCROS0243');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (47, 'PUECH ALEXIS', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(47,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(47,'IOTCROS0196');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (48, 'KAUFFMANN MARION', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(48,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(48,'IOTCROS0113');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (49, 'NGOUDZO WALIASSAOUN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(49,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(49,'IOTCROS0179');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (50, 'LE GUENEC MORGAN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(50,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(50,'IOTCROS0990');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (51, 'DELPONT CHRISTOPHE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(51,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(51,'IOTCROS0069');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (52, 'LE GUERNIC MORGAN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(52,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(52,'IOTCROS0137');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (53, 'TARNET GERARD', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(53,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(53,'IOTCROS0227');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (54, 'LAFFONT SEBASTIEN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(54,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(54,'IOTCROS0124');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (55, 'CORBREJAUN LEOPOLD', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(55,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(55,'IOTCROS0059');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (56, 'BAILLOUT CHRISTOPHE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(56,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(56,'IOTCROS0015');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (57, 'THIRIAT WILLY', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(57,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(57,'IOTCROS0232');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (58, 'LANDIER HERVE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(58,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(58,'IOTCROS0127');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (59, 'GROULT THIBAULT', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(59,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(59,'IOTCROS0097');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (60, 'ROBERT DAVID', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(60,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(60,'IOTCROS0210');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (61, 'PERRET YVES DENIS', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(61,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(61,'IOTCROS0186');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (62, 'PICORON NICOL', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(62,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(62,'IOTCROS0187');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (63, 'RODRIGUEZ HUGO', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(63,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(63,'IOTCROS0211');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (64, 'LAHADJI RAPHAEL', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(64,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(64,'IOTCROS0125');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (65, 'CHATEL FRANCOIS', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(65,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(65,'IOTCROS0048');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (66, 'COUTINHO FRANCOIS', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(66,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(66,'IOTCROS0061');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (67, 'GAGE KLEBERT', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(67,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(67,'IOTCROS0087');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (68, 'BEATRIX MELVIN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(68,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(68,'IOTCROS0017');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (69, 'MARTINEZ SARAH', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(69,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(69,'IOTCROS0162');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (70, 'TENOR BERTRAND', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(70,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(70,'IOTCROS0230');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (71, 'LE FRANC ALAIN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(71,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(71,'IOTCROS0136');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (72, 'NAERT DAMIEN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(72,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(72,'IOTCROS0178');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (73, 'ULDARICH NAUCHE MIGUEL', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(73,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(73,'IOTCROS0238');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (74, 'MASSEY YOLUENE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(74,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(74,'IOTCROS0163');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (75, 'VINCENT DORIAN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(75,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(75,'IOTCROS0246');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (76, 'KUMARA RAJAPURAGE ASNEESON', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(76,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(76,'IOTCROS0679');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (77, 'UDAYAPRIYA HEWA BAMBARENDAGE PASINDU DILANJANA', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(77,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(77,'IOTCROS0685');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (78, 'WEERAKOON ERANGA MANOJ', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(78,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(78,'IOTCROS0678');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (79, 'LARASE UDIN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(79,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(79,'IOTCROS0392');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (80, 'TURISNO', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(80,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(80,'IOTCROS0424');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (81, 'SATAMANA', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(81,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(81,'IOTCROS0995');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (82, 'WAWAN SETIAWAN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(82,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(82,'IOTCROS0428');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (83, 'MAHYUDIN ADAM', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(83,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(83,'IOTCROS0991');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (84, 'WIGUNA HARRI KRISNA', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(84,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(84,'IOTCROS1004');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (85, 'ANDRIANTO IWAN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(85,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(85,'IOTCROS0381');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (86, 'KESUMA SRI WENDA', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(86,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(86,'IOTCROS0987');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (87, 'IBROHIM AHMAD', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(87,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(87,'IOTCROS0388');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (88, 'MUHARAM DIANA', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(88,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(88,'IOTCROS0394');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (89, 'PUJIIYANTO URIP', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(89,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(89,'IOTCROS0402');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (90, 'SAFII MOCHAMAT', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(90,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(90,'IOTCROS0994');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (91, 'SANJOYO PARTO', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(91,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(91,'IOTCROS0399');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (92, 'SUPRAPTONO TEGUH', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(92,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(92,'IOTCROS0418');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (93, 'SUPRIYANTO AGUS', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(93,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(93,'IOTCROS0999');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (94, 'RIYADI SLAMET', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(94,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(94,'IOTCROS0405');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (95, 'DWIGUNO SEPTYA', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(95,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(95,'IOTCROS0985');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (96, 'ZUBEIR ISMINOV', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(96,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(96,'IOTCROS0429');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (97, 'AWALUDIN AZIS', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(97,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(97,'IOTCROS0383');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (98, 'TAOPIK OPIK', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(98,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(98,'IOTCROS0423');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (99, 'IRWANTO', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(99,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(99,'IOTCROS0389');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (100, 'SUBAGIA LILIK HERU', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(100,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(100,'IOTCROS0413');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (101, 'SURYANA NANA', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(101,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(101,'IOTCROS0421');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (102, 'WAHYUDIN', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(102,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(102,'IOTCROS0426');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (103, 'SHIRAISHI TUGIO', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(103,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(103,'IOTCROS0996');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (104, 'AOYAMA TAKASHI', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(104,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(104,'IOTCROS0983');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (105, 'TOTSUKA TAKASHI', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(105,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(105,'IOTCROS1003');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (106, 'SATO KAZUHIKO', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(106,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(106,'IOTCROS0411');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (107, 'SUZUKI KATSUHIRO', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(107,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(107,'IOTCROS1000');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (108, 'MINAMITAKE HIROMI', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(108,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(108,'IOTCROS0404');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (109, 'MURAKAMI CHIAKI', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(109,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(109,'IOTCROS0992');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (110, 'ISHISE TSUTOMU', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(110,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(110,'IOTCROS0430');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (111, 'TOKIYOSHI MASAYUKI', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(111,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(111,'IOTCROS1002');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (112, 'YAMAGUCHI KO', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(112,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(112,'IOTCROS1005');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (113, 'NAKAYAMA RYUSUKE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(113,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(113,'IOTCROS0407');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (114, 'FURUUCHI KATSUJI', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(114,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(114,'IOTCROS0397');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (115, 'HARUKAWA HIDEO', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(115,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(115,'IOTCROS0986');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (116, 'NAKAOJI RYO', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(116,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(116,'IOTCROS0406');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (117, 'SATOH MANABU', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(117,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(117,'IOTCROS0412');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (118, 'OCUP', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(118,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(118,'IOTCROS9997');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (119, 'DCF Senne (IRD)', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(119,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(119,'IOTCROS9998');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (120, 'DCF Senne (TAAF)', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(120,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(120,'IOTCROS9999');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (121, 'KRISNEN MURDAY', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(121,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(121,'IOTCROS0988');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (122, 'DEVANAND BOLAKY', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(122,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(122,'IOTCROS0984');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (123, 'SREEKEESSOON POORNAH SINGH', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(123,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(123,'IOTCROS0998');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (124, 'LATCHANNA HEMRAJ', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(124,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(124,'IOTCROS0989');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (125, 'RAMASAWMY S', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(125,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(125,'IOTCROS0993');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (126, 'SAM GEUN HA', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(126,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(126,'IOTCROS0458');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (127, 'SU HYUNG KIM', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(127,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(127,'IOTCROS0449');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (128, 'YOON GIL LEE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(128,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(128,'IOTCROS0460');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (129, 'YU RI JUNG', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(129,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(129,'IOTCROS0475');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (130, 'JUN CHEOL LEE', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(130,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(130,'IOTCROS0442');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (131, 'CHANDRAKUMARA K. SURAJ', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(131,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(131,'IOTCROS0696');
INSERT INTO ros_common.contact(id, full_name, active) OVERRIDING SYSTEM VALUE VALUES (132, 'DHARMENTHIRA WIMALANATHA', TRUE);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(132,'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) OVERRIDING SYSTEM VALUE VALUES(132,'IOTCROS0681');
INSERT INTO ros_common.contact(id, full_name, active, email, phone, comment, nationality_code) OVERRIDING SYSTEM VALUE VALUES (133, 'ROCHE THOMAS', TRUE, 'Thomas.Roche@developpement-durable.gouv.fr', '+33 1 40 81 97 51', 'Ministère de l''Ecologie, du Développement durable et de l''Energie', 'FRA');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(133,'FP');
INSERT INTO ros_common.contact(id, full_name, active, email, phone, comment, nationality_code) OVERRIDING SYSTEM VALUE VALUES (134, 'LE GALLOUDEC FABIEN', TRUE, 'fabien.le-galloudec@developpement-durable.gouv.fr', NULL, 'Direction des Peches Maritimes et de l''Aquaculture', 'FRA');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(134,'FP');
INSERT INTO ros_common.contact(id, full_name, active, email, phone, comment, nationality_code) OVERRIDING SYSTEM VALUE VALUES (135, 'MELARD ANAIS', TRUE, 'anais.melard@agriculture.gouv.fr', '+33140819531', 'Direction des Pêches Maritimes et de l''Agriculture (DPMA), Ministère de l''Agriculture et de l''Alimentation, Tour Séquoia 92055 La Défense', 'FRA');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(135,'FP');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(76,'FP');
UPDATE ros_common.contact SET nationality_code = 'LKA' WHERE id = 76;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(77,'FP');
UPDATE ros_common.contact SET nationality_code = 'LKA' WHERE id = 77;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(78,'FP');
UPDATE ros_common.contact SET nationality_code = 'LKA' WHERE id = 78;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(110,'FP');
UPDATE ros_common.contact SET nationality_code = 'JPN' WHERE id = 110;
UPDATE ros_common.contact SET email = 'aco20320@par.odn.ne.jp' WHERE id = 110;
UPDATE ros_common.contact SET phone = '+81 54-336-5834' WHERE id = 110;
UPDATE ros_common.contact SET comment = 'National Research Institute of Far Seas Fisheries (NRIFSF), Japan Fisheries Research and Education Agency, 5-7-1, Orido, Shimizu-Ward, Shizuoka-City, Shizuoka, Japan 424-8633 - http://fsf.fra.affrc.go.jp/' WHERE id = 110;
INSERT INTO ros_common.contact(id, full_name, active, email, phone, comment, nationality_code) OVERRIDING SYSTEM VALUE VALUES (136, 'UNKNOWN', TRUE, NULL, NULL, NULL, 'ESP');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(136,'FP');
INSERT INTO ros_common.contact(id, full_name, active, email, phone, comment, nationality_code) OVERRIDING SYSTEM VALUE VALUES (137, 'ELENA CONSUEGRA ALCALDE', TRUE, 'econsuegra@mapa.es', '34913476066', 'Fisheries General Secretariat, Ministry of Agriculture, Fisheries and Food, c/ Velázquez, 144', 'ESP');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(137,'FP');
INSERT INTO ros_common.contact(id, full_name, active, email, phone, comment, nationality_code) OVERRIDING SYSTEM VALUE VALUES (138, 'GLORIA DEL CERRO MARTÍN', TRUE, 'gcerro@mapama.es', '913475940', 'Secretaria General de Pesca, Ministerio de Agricultura, Pesca, Alimentación y Medio Ambiente, C/ de Velázquez 144', 'ESP');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(138,'FP');
INSERT INTO ros_common.contact(id, full_name, active, email, phone, comment, nationality_code) OVERRIDING SYSTEM VALUE VALUES (139, 'MELLISSA JOSEPH', TRUE, 'mjoseph@sfa.sc', NULL, NULL, 'SYC');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(139,'FP');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(121,'FP');
UPDATE ros_common.contact SET nationality_code = 'MUS' WHERE id = 121;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(122,'FP');
UPDATE ros_common.contact SET nationality_code = 'MUS' WHERE id = 122;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(123,'FP');
UPDATE ros_common.contact SET nationality_code = 'MUS' WHERE id = 123;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(124,'FP');
UPDATE ros_common.contact SET nationality_code = 'MUS' WHERE id = 124;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(125,'FP');
UPDATE ros_common.contact SET nationality_code = 'MUS' WHERE id = 125;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(126,'FP');
UPDATE ros_common.contact SET nationality_code = 'KOR' WHERE id = 126;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(127,'FP');
UPDATE ros_common.contact SET nationality_code = 'KOR' WHERE id = 127;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(128,'FP');
UPDATE ros_common.contact SET nationality_code = 'KOR' WHERE id = 128;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(129,'FP');
UPDATE ros_common.contact SET nationality_code = 'KOR' WHERE id = 129;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(130,'FP');
UPDATE ros_common.contact SET nationality_code = 'KOR' WHERE id = 130;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(131,'FP');
UPDATE ros_common.contact SET nationality_code = 'LKA' WHERE id = 131;
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(132,'FP');
UPDATE ros_common.contact SET nationality_code = 'LKA' WHERE id = 132;
INSERT INTO ros_common.contact(id, full_name, active, email, phone, comment, nationality_code) OVERRIDING SYSTEM VALUE VALUES (140, 'TERESA MOLINA SCHMID', TRUE, 'tmolina@mapa.es', NULL, 'Subdirección General de Acuerdos y ORP, Secretaría General de Pesca, Ministerio de Agricultura, Pesca y Alimentación, c/ Velázquez, 144, Madrid', 'ESP');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(140,'FP');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (141, 'Vandennoortgate Franck', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(141,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (142, 'Le Saint Michel', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(142,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (143, 'Lefranc Alain', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(143,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (144, 'Tatibouet Jean-Marc', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(144,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (145, 'Perrin Mathieu', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(145,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (146, 'Payet Frederic', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(146,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (147, 'Hubert Jean-Max', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(147,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (148, 'Francois Marie-George', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(148,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (149, 'Techer Elphage', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(149,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (150, 'Landier Hervé', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(150,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (151, 'Deshayes Mathieu', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(151,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (152, '[inconnu] [inconnu]', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(152,'SK');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(152,'FM');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (153, 'Slimhane Kemat', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(153,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (154, 'Briand Pascal', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(154,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (155, 'Danic Fabrice', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(155,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (156, 'Fasseur Ludovic', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(156,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (157, 'Milcent Antoine', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(157,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (158, 'Lautroux Stéphane', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(158,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (159, 'Millau Frederic', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(159,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (160, 'Lecossec Yann', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(160,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (161, 'Rousseau Jonathan', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(161,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (162, 'Le Pape Fred', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(162,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (163, 'Aoustin Didier', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(163,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (164, 'Popowicz Thierry', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(164,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (165, 'Frigout Daniel', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(165,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (166, 'Raffestin Patrice', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(166,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (167, 'Aubras Nataniel', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(167,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (168, 'Berthier Philippe', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(168,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (169, 'Moutal Frédéric', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(169,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (170, 'Bengala José', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(170,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (171, 'Dijoux Robert', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(171,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (172, 'Chichery Michel', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(172,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (173, 'Basile Wilfried', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(173,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (174, 'Ouillon Bruno', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(174,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (175, 'Mussard Fabrice', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(175,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (176, 'Vincent Anthony', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(176,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (177, 'Faivre Christy', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(177,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (178, 'Lebian Ruddy', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(178,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (179, 'Hervagault Eric', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(179,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (180, 'Vergoz Jean', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(180,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (181, 'Le Guenec Morgan', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(181,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (182, 'Genetet Mickael', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(182,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (183, 'Cartron Jérôme', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(183,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (184, 'Verdière Pascal', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(184,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (185, 'Le Guernic Morgan', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(185,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (186, 'Tarnet Gérard', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(186,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (187, 'Laffont Sébastien', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(187,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (188, 'Corbrejaun Leopold', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(188,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (189, 'Thiriat Willy', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(189,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (190, 'Herledan Didier', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(190,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (191, 'Robert David', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(191,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (192, 'Madic Bruno', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(192,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (193, 'Chatel François', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(193,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (194, 'Coutinho François', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(194,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (195, 'Gage Klébert', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(195,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (196, 'Ténor Bertrand', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(196,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (197, 'Le Franc Alain', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(197,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (198, 'Vincent Dorian', TRUE, NULL);
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(198,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (199, 'Chang Yung Feng', TRUE, 'TWN');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(199,'FM');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (200, 'LI ZHU YOU', TRUE, 'CHN');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(200,'SK');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(200,'FM');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (201, 'ANTORA JR CABANIRO YLADE', TRUE, 'PHL');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(201,'SK');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(201,'FM');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (202, 'CHEN ZHI YOUNG', TRUE, 'CHN');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(202,'SK');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(202,'FM');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (203, 'Mr.Zhuang Shi Hai', TRUE, 'CHN');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(203,'SK');
INSERT INTO ros_common.contact(id, full_name, active, nationality_code) OVERRIDING SYSTEM VALUE VALUES (204, 'Ling Chin Tsan', TRUE, 'TWN');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES(204,'SK');
