
select setval('ros_common.contact_id_seq', (select max(id) from ros_common.contact));

INSERT INTO ros_common.contact(full_name, active, nationality_code) VALUES ('HARDY ADRIEN', true,  'FRA');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) VALUES (205, 'IOTCROS0099');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES (205, 'OB');

INSERT INTO ros_common.contact(full_name, active,  nationality_code) VALUES ('QUIQUEMPOIS VINCENT', true,  'FRA');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) VALUES (206, 'IOTCROS0198');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES (206, 'OB');

INSERT INTO ros_common.contact(full_name, active, nationality_code) VALUES ('VALADE ISABELLE', true, 'FRA');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) VALUES (207, 'IOTCROS0239');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES (207, 'OB');
INSERT INTO ros_common.contact(full_name, active, nationality_code, email, comment) VALUES ('LINTANF PHILIPPE', true, 'FRA', 'philippe.lintanf@agriculture.gouv.fr', 'Direction Générale des Affaires Maritimes, de la Pêche et de l''Aquaculture (DGAMPA)');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES (208, 'FP');

INSERT INTO ros_common.contact(full_name, active, nationality_code, email, comment) VALUES ('PAUMIER ALEXIS', true, 'FRA', 'alexis.paumier@agriculture.gouv.fr', 'Direction Générale des Affaires Maritimes, de la Pêche et de l''Aquaculture (DGAMPA)');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES (209, 'FP');

INSERT INTO ros_common.contact(full_name, active, nationality_code) VALUES ('KLEFFER YVES,', true, 'FRA');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES (162, 'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) VALUES (162, 'IOTCROS0117');

INSERT INTO ros_common.contact(full_name, active, nationality_code) VALUES ('GUILLON NICOLAS', true, 'FRA');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES (163, 'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) VALUES (163, 'IOTCROS0098');

INSERT INTO ros_common.contact(full_name, active, nationality_code) VALUES ('BEGUE JOHAN', true, 'FRA');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES (164, 'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) VALUES (164, 'IOTCROS0018');

INSERT INTO ros_common.contact(full_name, active, nationality_code) VALUES ('LOUSSOUARN FRANCK', true, 'FRA');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES (165, 'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) VALUES (165, 'IOTCROS0155');

INSERT INTO ros_common.contact(full_name, active, nationality_code) VALUES ('POURTAU MARTIN', true, 'FRA');
INSERT INTO ros_common.contact_role(contact_id, role_code) VALUES (166, 'OB');
INSERT INTO ros_common.observer(contact_id, iotc_observer_identifier) VALUES (166, 'IOTCROS0194');

UPDATE ros_common.contact_role SET contact_id = 70 WHERE contact_id = 196;
UPDATE ros_common.observer SET contact_id = 70 WHERE contact_id = 196;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 70 WHERE fishing_master_id = 196;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 70 WHERE skipper_id = 196;
UPDATE ros_gn.observer_data SET creator_id = 70 WHERE creator_id = 196;
UPDATE ros_gn.observer_data SET submitter_id = 70 WHERE submitter_id = 196;
UPDATE ros_gn.tag_details SET tag_finder_id = 70 WHERE tag_finder_id = 196;
UPDATE ros_ll.observer_data SET creator_id = 70 WHERE creator_id = 196;
UPDATE ros_ll.observer_data SET submitter_id = 70 WHERE submitter_id = 196;
UPDATE ros_ll.tag_details SET tag_finder_id = 70 WHERE tag_finder_id = 196;
UPDATE ros_pl.observer_data SET creator_id = 70 WHERE creator_id = 196;
UPDATE ros_pl.observer_data SET submitter_id = 70 WHERE submitter_id = 196;
UPDATE ros_pl.tag_details SET tag_finder_id = 70 WHERE tag_finder_id = 196;
UPDATE ros_ps.observer_data SET creator_id = 70 WHERE creator_id = 196;
UPDATE ros_ps.observer_data SET submitter_id = 70 WHERE submitter_id = 196;
UPDATE ros_ps.tag_details SET tag_finder_id = 70 WHERE tag_finder_id = 196;
DELETE FROM ros_common.contact WHERE id = 196;


UPDATE ros_common.contact_role SET contact_id = 57 WHERE contact_id = 189;
UPDATE ros_common.observer SET contact_id = 57 WHERE contact_id = 189;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 57 WHERE fishing_master_id = 189;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 57 WHERE skipper_id = 189;
UPDATE ros_gn.observer_data SET creator_id = 57 WHERE creator_id = 189;
UPDATE ros_gn.observer_data SET submitter_id = 57 WHERE submitter_id = 189;
UPDATE ros_gn.tag_details SET tag_finder_id = 57 WHERE tag_finder_id = 189;
UPDATE ros_ll.observer_data SET creator_id = 57 WHERE creator_id = 189;
UPDATE ros_ll.observer_data SET submitter_id = 57 WHERE submitter_id = 189;
UPDATE ros_ll.tag_details SET tag_finder_id = 57 WHERE tag_finder_id = 189;
UPDATE ros_pl.observer_data SET creator_id = 57 WHERE creator_id = 189;
UPDATE ros_pl.observer_data SET submitter_id = 57 WHERE submitter_id = 189;
UPDATE ros_pl.tag_details SET tag_finder_id = 57 WHERE tag_finder_id = 189;
UPDATE ros_ps.observer_data SET creator_id = 57 WHERE creator_id = 189;
UPDATE ros_ps.observer_data SET submitter_id = 57 WHERE submitter_id = 189;
UPDATE ros_ps.tag_details SET tag_finder_id = 57 WHERE tag_finder_id = 189;
DELETE FROM ros_common.contact WHERE id = 189;

UPDATE ros_common.contact_role SET contact_id = 58 WHERE contact_id = 150;
UPDATE ros_common.observer SET contact_id = 58 WHERE contact_id = 150;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 58 WHERE fishing_master_id = 150;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 58 WHERE skipper_id = 150;
UPDATE ros_gn.observer_data SET creator_id = 58 WHERE creator_id = 150;
UPDATE ros_gn.observer_data SET submitter_id = 58 WHERE submitter_id = 150;
UPDATE ros_gn.tag_details SET tag_finder_id = 58 WHERE tag_finder_id = 150;
UPDATE ros_ll.observer_data SET creator_id = 58 WHERE creator_id = 150;
UPDATE ros_ll.observer_data SET submitter_id = 58 WHERE submitter_id = 150;
UPDATE ros_ll.tag_details SET tag_finder_id = 58 WHERE tag_finder_id = 150;
UPDATE ros_pl.observer_data SET creator_id = 58 WHERE creator_id = 150;
UPDATE ros_pl.observer_data SET submitter_id = 58 WHERE submitter_id = 150;
UPDATE ros_pl.tag_details SET tag_finder_id = 58 WHERE tag_finder_id = 150;
UPDATE ros_ps.observer_data SET creator_id = 58 WHERE creator_id = 150;
UPDATE ros_ps.observer_data SET submitter_id = 58 WHERE submitter_id = 150;
UPDATE ros_ps.tag_details SET tag_finder_id = 58 WHERE tag_finder_id = 150;
DELETE FROM ros_common.contact WHERE id = 150;
UPDATE ros_common.contact_role SET contact_id = 65 WHERE contact_id = 193;
UPDATE ros_common.observer SET contact_id = 65 WHERE contact_id = 193;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 65 WHERE fishing_master_id = 193;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 65 WHERE skipper_id = 193;
UPDATE ros_gn.observer_data SET creator_id = 65 WHERE creator_id = 193;
UPDATE ros_gn.observer_data SET submitter_id = 65 WHERE submitter_id = 193;
UPDATE ros_gn.tag_details SET tag_finder_id = 65 WHERE tag_finder_id = 193;
UPDATE ros_ll.observer_data SET creator_id = 65 WHERE creator_id = 193;
UPDATE ros_ll.observer_data SET submitter_id = 65 WHERE submitter_id = 193;
UPDATE ros_ll.tag_details SET tag_finder_id = 65 WHERE tag_finder_id = 193;
UPDATE ros_pl.observer_data SET creator_id = 65 WHERE creator_id = 193;
UPDATE ros_pl.observer_data SET submitter_id = 65 WHERE submitter_id = 193;
UPDATE ros_pl.tag_details SET tag_finder_id = 65 WHERE tag_finder_id = 193;
UPDATE ros_ps.observer_data SET creator_id = 65 WHERE creator_id = 193;
UPDATE ros_ps.observer_data SET submitter_id = 65 WHERE submitter_id = 193;
UPDATE ros_ps.tag_details SET tag_finder_id = 65 WHERE tag_finder_id = 193;
DELETE FROM ros_common.contact WHERE id = 193;
UPDATE ros_common.contact_role SET contact_id = 52 WHERE contact_id = 185;
UPDATE ros_common.observer SET contact_id = 52 WHERE contact_id = 185;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 52 WHERE fishing_master_id = 185;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 52 WHERE skipper_id = 185;
UPDATE ros_gn.observer_data SET creator_id = 52 WHERE creator_id = 185;
UPDATE ros_gn.observer_data SET submitter_id = 52 WHERE submitter_id = 185;
UPDATE ros_gn.tag_details SET tag_finder_id = 52 WHERE tag_finder_id = 185;
UPDATE ros_ll.observer_data SET creator_id = 52 WHERE creator_id = 185;
UPDATE ros_ll.observer_data SET submitter_id = 52 WHERE submitter_id = 185;
UPDATE ros_ll.tag_details SET tag_finder_id = 52 WHERE tag_finder_id = 185;
UPDATE ros_pl.observer_data SET creator_id = 52 WHERE creator_id = 185;
UPDATE ros_pl.observer_data SET submitter_id = 52 WHERE submitter_id = 185;
UPDATE ros_pl.tag_details SET tag_finder_id = 52 WHERE tag_finder_id = 185;
UPDATE ros_ps.observer_data SET creator_id = 52 WHERE creator_id = 185;
UPDATE ros_ps.observer_data SET submitter_id = 52 WHERE submitter_id = 185;
UPDATE ros_ps.tag_details SET tag_finder_id = 52 WHERE tag_finder_id = 185;
DELETE FROM ros_common.contact WHERE id = 185;
UPDATE ros_common.contact_role SET contact_id = 11 WHERE contact_id = 156;
UPDATE ros_common.observer SET contact_id = 11 WHERE contact_id = 156;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 11 WHERE fishing_master_id = 156;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 11 WHERE skipper_id = 156;
UPDATE ros_gn.observer_data SET creator_id = 11 WHERE creator_id = 156;
UPDATE ros_gn.observer_data SET submitter_id = 11 WHERE submitter_id = 156;
UPDATE ros_gn.tag_details SET tag_finder_id = 11 WHERE tag_finder_id = 156;
UPDATE ros_ll.observer_data SET creator_id = 11 WHERE creator_id = 156;
UPDATE ros_ll.observer_data SET submitter_id = 11 WHERE submitter_id = 156;
UPDATE ros_ll.tag_details SET tag_finder_id = 11 WHERE tag_finder_id = 156;
UPDATE ros_pl.observer_data SET creator_id = 11 WHERE creator_id = 156;
UPDATE ros_pl.observer_data SET submitter_id = 11 WHERE submitter_id = 156;
UPDATE ros_pl.tag_details SET tag_finder_id = 11 WHERE tag_finder_id = 156;
UPDATE ros_ps.observer_data SET creator_id = 11 WHERE creator_id = 156;
UPDATE ros_ps.observer_data SET submitter_id = 11 WHERE submitter_id = 156;
UPDATE ros_ps.tag_details SET tag_finder_id = 11 WHERE tag_finder_id = 156;
DELETE FROM ros_common.contact WHERE id = 156;
UPDATE ros_common.contact_role SET contact_id = 67 WHERE contact_id = 195;
UPDATE ros_common.observer SET contact_id = 67 WHERE contact_id = 195;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 67 WHERE fishing_master_id = 195;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 67 WHERE skipper_id = 195;
UPDATE ros_gn.observer_data SET creator_id = 67 WHERE creator_id = 195;
UPDATE ros_gn.observer_data SET submitter_id = 67 WHERE submitter_id = 195;
UPDATE ros_gn.tag_details SET tag_finder_id = 67 WHERE tag_finder_id = 195;
UPDATE ros_ll.observer_data SET creator_id = 67 WHERE creator_id = 195;
UPDATE ros_ll.observer_data SET submitter_id = 67 WHERE submitter_id = 195;
UPDATE ros_ll.tag_details SET tag_finder_id = 67 WHERE tag_finder_id = 195;
UPDATE ros_pl.observer_data SET creator_id = 67 WHERE creator_id = 195;
UPDATE ros_pl.observer_data SET submitter_id = 67 WHERE submitter_id = 195;
UPDATE ros_pl.tag_details SET tag_finder_id = 67 WHERE tag_finder_id = 195;
UPDATE ros_ps.observer_data SET creator_id = 67 WHERE creator_id = 195;
UPDATE ros_ps.observer_data SET submitter_id = 67 WHERE submitter_id = 195;
UPDATE ros_ps.tag_details SET tag_finder_id = 67 WHERE tag_finder_id = 195;
DELETE FROM ros_common.contact WHERE id = 195;
UPDATE ros_common.contact_role SET contact_id = 60 WHERE contact_id = 191;
UPDATE ros_common.observer SET contact_id = 60 WHERE contact_id = 191;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 60 WHERE fishing_master_id = 191;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 60 WHERE skipper_id = 191;
UPDATE ros_gn.observer_data SET creator_id = 60 WHERE creator_id = 191;
UPDATE ros_gn.observer_data SET submitter_id = 60 WHERE submitter_id = 191;
UPDATE ros_gn.tag_details SET tag_finder_id = 60 WHERE tag_finder_id = 191;
UPDATE ros_ll.observer_data SET creator_id = 60 WHERE creator_id = 191;
UPDATE ros_ll.observer_data SET submitter_id = 60 WHERE submitter_id = 191;
UPDATE ros_ll.tag_details SET tag_finder_id = 60 WHERE tag_finder_id = 191;
UPDATE ros_pl.observer_data SET creator_id = 60 WHERE creator_id = 191;
UPDATE ros_pl.observer_data SET submitter_id = 60 WHERE submitter_id = 191;
UPDATE ros_pl.tag_details SET tag_finder_id = 60 WHERE tag_finder_id = 191;
UPDATE ros_ps.observer_data SET creator_id = 60 WHERE creator_id = 191;
UPDATE ros_ps.observer_data SET submitter_id = 60 WHERE submitter_id = 191;
UPDATE ros_ps.tag_details SET tag_finder_id = 60 WHERE tag_finder_id = 191;
DELETE FROM ros_common.contact WHERE id = 191;
UPDATE ros_common.contact_role SET contact_id = 32 WHERE contact_id = 171;
UPDATE ros_common.observer SET contact_id = 32 WHERE contact_id = 171;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 32 WHERE fishing_master_id = 171;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 32 WHERE skipper_id = 171;
UPDATE ros_gn.observer_data SET creator_id = 32 WHERE creator_id = 171;
UPDATE ros_gn.observer_data SET submitter_id = 32 WHERE submitter_id = 171;
UPDATE ros_gn.tag_details SET tag_finder_id = 32 WHERE tag_finder_id = 171;
UPDATE ros_ll.observer_data SET creator_id = 32 WHERE creator_id = 171;
UPDATE ros_ll.observer_data SET submitter_id = 32 WHERE submitter_id = 171;
UPDATE ros_ll.tag_details SET tag_finder_id = 32 WHERE tag_finder_id = 171;
UPDATE ros_pl.observer_data SET creator_id = 32 WHERE creator_id = 171;
UPDATE ros_pl.observer_data SET submitter_id = 32 WHERE submitter_id = 171;
UPDATE ros_pl.tag_details SET tag_finder_id = 32 WHERE tag_finder_id = 171;
UPDATE ros_ps.observer_data SET creator_id = 32 WHERE creator_id = 171;
UPDATE ros_ps.observer_data SET submitter_id = 32 WHERE submitter_id = 171;
UPDATE ros_ps.tag_details SET tag_finder_id = 32 WHERE tag_finder_id = 171;
DELETE FROM ros_common.contact WHERE id = 171;
UPDATE ros_common.contact_role SET contact_id = 31 WHERE contact_id = 170;
UPDATE ros_common.observer SET contact_id = 31 WHERE contact_id = 170;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 31 WHERE fishing_master_id = 170;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 31 WHERE skipper_id = 170;
UPDATE ros_gn.observer_data SET creator_id = 31 WHERE creator_id = 170;
UPDATE ros_gn.observer_data SET submitter_id = 31 WHERE submitter_id = 170;
UPDATE ros_gn.tag_details SET tag_finder_id = 31 WHERE tag_finder_id = 170;
UPDATE ros_ll.observer_data SET creator_id = 31 WHERE creator_id = 170;
UPDATE ros_ll.observer_data SET submitter_id = 31 WHERE submitter_id = 170;
UPDATE ros_ll.tag_details SET tag_finder_id = 31 WHERE tag_finder_id = 170;
UPDATE ros_pl.observer_data SET creator_id = 31 WHERE creator_id = 170;
UPDATE ros_pl.observer_data SET submitter_id = 31 WHERE submitter_id = 170;
UPDATE ros_pl.tag_details SET tag_finder_id = 31 WHERE tag_finder_id = 170;
UPDATE ros_ps.observer_data SET creator_id = 31 WHERE creator_id = 170;
UPDATE ros_ps.observer_data SET submitter_id = 31 WHERE submitter_id = 170;
UPDATE ros_ps.tag_details SET tag_finder_id = 31 WHERE tag_finder_id = 170;
DELETE FROM ros_common.contact WHERE id = 170;
UPDATE ros_common.contact_role SET contact_id = 40 WHERE contact_id = 146;
UPDATE ros_common.observer SET contact_id = 40 WHERE contact_id = 146;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 40 WHERE fishing_master_id = 146;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 40 WHERE skipper_id = 146;
UPDATE ros_gn.observer_data SET creator_id = 40 WHERE creator_id = 146;
UPDATE ros_gn.observer_data SET submitter_id = 40 WHERE submitter_id = 146;
UPDATE ros_gn.tag_details SET tag_finder_id = 40 WHERE tag_finder_id = 146;
UPDATE ros_ll.observer_data SET creator_id = 40 WHERE creator_id = 146;
UPDATE ros_ll.observer_data SET submitter_id = 40 WHERE submitter_id = 146;
UPDATE ros_ll.tag_details SET tag_finder_id = 40 WHERE tag_finder_id = 146;
UPDATE ros_pl.observer_data SET creator_id = 40 WHERE creator_id = 146;
UPDATE ros_pl.observer_data SET submitter_id = 40 WHERE submitter_id = 146;
UPDATE ros_pl.tag_details SET tag_finder_id = 40 WHERE tag_finder_id = 146;
UPDATE ros_ps.observer_data SET creator_id = 40 WHERE creator_id = 146;
UPDATE ros_ps.observer_data SET submitter_id = 40 WHERE submitter_id = 146;
UPDATE ros_ps.tag_details SET tag_finder_id = 40 WHERE tag_finder_id = 146;
DELETE FROM ros_common.contact WHERE id = 146;
UPDATE ros_common.contact_role SET contact_id = 30 WHERE contact_id = 169;
UPDATE ros_common.observer SET contact_id = 30 WHERE contact_id = 169;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 30 WHERE fishing_master_id = 169;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 30 WHERE skipper_id = 169;
UPDATE ros_gn.observer_data SET creator_id = 30 WHERE creator_id = 169;
UPDATE ros_gn.observer_data SET submitter_id = 30 WHERE submitter_id = 169;
UPDATE ros_gn.tag_details SET tag_finder_id = 30 WHERE tag_finder_id = 169;
UPDATE ros_ll.observer_data SET creator_id = 30 WHERE creator_id = 169;
UPDATE ros_ll.observer_data SET submitter_id = 30 WHERE submitter_id = 169;
UPDATE ros_ll.tag_details SET tag_finder_id = 30 WHERE tag_finder_id = 169;
UPDATE ros_pl.observer_data SET creator_id = 30 WHERE creator_id = 169;
UPDATE ros_pl.observer_data SET submitter_id = 30 WHERE submitter_id = 169;
UPDATE ros_pl.tag_details SET tag_finder_id = 30 WHERE tag_finder_id = 169;
UPDATE ros_ps.observer_data SET creator_id = 30 WHERE creator_id = 169;
UPDATE ros_ps.observer_data SET submitter_id = 30 WHERE submitter_id = 169;
UPDATE ros_ps.tag_details SET tag_finder_id = 30 WHERE tag_finder_id = 169;
DELETE FROM ros_common.contact WHERE id = 169;


UPDATE ros_common.contact_role SET contact_id = 37 WHERE contact_id = 163;
UPDATE ros_common.observer SET contact_id = 37 WHERE contact_id = 163;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 37 WHERE fishing_master_id = 163;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 37 WHERE skipper_id = 163;
UPDATE ros_gn.observer_data SET creator_id = 37 WHERE creator_id = 163;
UPDATE ros_gn.observer_data SET submitter_id = 37 WHERE submitter_id = 163;
UPDATE ros_gn.tag_details SET tag_finder_id = 37 WHERE tag_finder_id = 163;
UPDATE ros_ll.observer_data SET creator_id = 37 WHERE creator_id = 163;
UPDATE ros_ll.observer_data SET submitter_id = 37 WHERE submitter_id = 163;
UPDATE ros_ll.tag_details SET tag_finder_id = 37 WHERE tag_finder_id = 163;
UPDATE ros_pl.observer_data SET creator_id = 37 WHERE creator_id = 163;
UPDATE ros_pl.observer_data SET submitter_id = 37 WHERE submitter_id = 163;
UPDATE ros_pl.tag_details SET tag_finder_id = 37 WHERE tag_finder_id = 163;
UPDATE ros_ps.observer_data SET creator_id = 37 WHERE creator_id = 163;
UPDATE ros_ps.observer_data SET submitter_id = 37 WHERE submitter_id = 163;
UPDATE ros_ps.tag_details SET tag_finder_id = 37 WHERE tag_finder_id = 163;
DELETE FROM ros_common.contact WHERE id = 163;
UPDATE ros_common.contact_role SET contact_id = 25 WHERE contact_id = 167;
UPDATE ros_common.observer SET contact_id = 25 WHERE contact_id = 167;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 25 WHERE fishing_master_id = 167;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 25 WHERE skipper_id = 167;
UPDATE ros_gn.observer_data SET creator_id = 25 WHERE creator_id = 167;
UPDATE ros_gn.observer_data SET submitter_id = 25 WHERE submitter_id = 167;
UPDATE ros_gn.tag_details SET tag_finder_id = 25 WHERE tag_finder_id = 167;
UPDATE ros_ll.observer_data SET creator_id = 25 WHERE creator_id = 167;
UPDATE ros_ll.observer_data SET submitter_id = 25 WHERE submitter_id = 167;
UPDATE ros_ll.tag_details SET tag_finder_id = 25 WHERE tag_finder_id = 167;
UPDATE ros_pl.observer_data SET creator_id = 25 WHERE creator_id = 167;
UPDATE ros_pl.observer_data SET submitter_id = 25 WHERE submitter_id = 167;
UPDATE ros_pl.tag_details SET tag_finder_id = 25 WHERE tag_finder_id = 167;
UPDATE ros_ps.observer_data SET creator_id = 25 WHERE creator_id = 167;
UPDATE ros_ps.observer_data SET submitter_id = 25 WHERE submitter_id = 167;
UPDATE ros_ps.tag_details SET tag_finder_id = 25 WHERE tag_finder_id = 167;
DELETE FROM ros_common.contact WHERE id = 167;
UPDATE ros_common.contact_role SET contact_id = 34 WHERE contact_id = 173;
UPDATE ros_common.observer SET contact_id = 34 WHERE contact_id = 173;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 34 WHERE fishing_master_id = 173;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 34 WHERE skipper_id = 173;
UPDATE ros_gn.observer_data SET creator_id = 34 WHERE creator_id = 173;
UPDATE ros_gn.observer_data SET submitter_id = 34 WHERE submitter_id = 173;
UPDATE ros_gn.tag_details SET tag_finder_id = 34 WHERE tag_finder_id = 173;
UPDATE ros_ll.observer_data SET creator_id = 34 WHERE creator_id = 173;
UPDATE ros_ll.observer_data SET submitter_id = 34 WHERE submitter_id = 173;
UPDATE ros_ll.tag_details SET tag_finder_id = 34 WHERE tag_finder_id = 173;
UPDATE ros_pl.observer_data SET creator_id = 34 WHERE creator_id = 173;
UPDATE ros_pl.observer_data SET submitter_id = 34 WHERE submitter_id = 173;
UPDATE ros_pl.tag_details SET tag_finder_id = 34 WHERE tag_finder_id = 173;
UPDATE ros_ps.observer_data SET creator_id = 34 WHERE creator_id = 173;
UPDATE ros_ps.observer_data SET submitter_id = 34 WHERE submitter_id = 173;
UPDATE ros_ps.tag_details SET tag_finder_id = 34 WHERE tag_finder_id = 173;
DELETE FROM ros_common.contact WHERE id = 173;
UPDATE ros_common.contact_role SET contact_id = 29 WHERE contact_id = 168;
UPDATE ros_common.observer SET contact_id = 29 WHERE contact_id = 168;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 29 WHERE fishing_master_id = 168;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 29 WHERE skipper_id = 168;
UPDATE ros_gn.observer_data SET creator_id = 29 WHERE creator_id = 168;
UPDATE ros_gn.observer_data SET submitter_id = 29 WHERE submitter_id = 168;
UPDATE ros_gn.tag_details SET tag_finder_id = 29 WHERE tag_finder_id = 168;
UPDATE ros_ll.observer_data SET creator_id = 29 WHERE creator_id = 168;
UPDATE ros_ll.observer_data SET submitter_id = 29 WHERE submitter_id = 168;
UPDATE ros_ll.tag_details SET tag_finder_id = 29 WHERE tag_finder_id = 168;
UPDATE ros_pl.observer_data SET creator_id = 29 WHERE creator_id = 168;
UPDATE ros_pl.observer_data SET submitter_id = 29 WHERE submitter_id = 168;
UPDATE ros_pl.tag_details SET tag_finder_id = 29 WHERE tag_finder_id = 168;
UPDATE ros_ps.observer_data SET creator_id = 29 WHERE creator_id = 168;
UPDATE ros_ps.observer_data SET submitter_id = 29 WHERE submitter_id = 168;
UPDATE ros_ps.tag_details SET tag_finder_id = 29 WHERE tag_finder_id = 168;
DELETE FROM ros_common.contact WHERE id = 168;
UPDATE ros_common.contact_role SET contact_id = 9 WHERE contact_id = 154;
UPDATE ros_common.observer SET contact_id = 9 WHERE contact_id = 154;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 9 WHERE fishing_master_id = 154;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 9 WHERE skipper_id = 154;
UPDATE ros_gn.observer_data SET creator_id = 9 WHERE creator_id = 154;
UPDATE ros_gn.observer_data SET submitter_id = 9 WHERE submitter_id = 154;
UPDATE ros_gn.tag_details SET tag_finder_id = 9 WHERE tag_finder_id = 154;
UPDATE ros_ll.observer_data SET creator_id = 9 WHERE creator_id = 154;
UPDATE ros_ll.observer_data SET submitter_id = 9 WHERE submitter_id = 154;
UPDATE ros_ll.tag_details SET tag_finder_id = 9 WHERE tag_finder_id = 154;
UPDATE ros_pl.observer_data SET creator_id = 9 WHERE creator_id = 154;
UPDATE ros_pl.observer_data SET submitter_id = 9 WHERE submitter_id = 154;
UPDATE ros_pl.tag_details SET tag_finder_id = 9 WHERE tag_finder_id = 154;
UPDATE ros_ps.observer_data SET creator_id = 9 WHERE creator_id = 154;
UPDATE ros_ps.observer_data SET submitter_id = 9 WHERE submitter_id = 154;
UPDATE ros_ps.tag_details SET tag_finder_id = 9 WHERE tag_finder_id = 154;
DELETE FROM ros_common.contact WHERE id = 154;
UPDATE ros_common.contact_role SET contact_id = 33 WHERE contact_id = 172;
UPDATE ros_common.observer SET contact_id = 33 WHERE contact_id = 172;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 33 WHERE fishing_master_id = 172;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 33 WHERE skipper_id = 172;
UPDATE ros_gn.observer_data SET creator_id = 33 WHERE creator_id = 172;
UPDATE ros_gn.observer_data SET submitter_id = 33 WHERE submitter_id = 172;
UPDATE ros_gn.tag_details SET tag_finder_id = 33 WHERE tag_finder_id = 172;
UPDATE ros_ll.observer_data SET creator_id = 33 WHERE creator_id = 172;
UPDATE ros_ll.observer_data SET submitter_id = 33 WHERE submitter_id = 172;
UPDATE ros_ll.tag_details SET tag_finder_id = 33 WHERE tag_finder_id = 172;
UPDATE ros_pl.observer_data SET creator_id = 33 WHERE creator_id = 172;
UPDATE ros_pl.observer_data SET submitter_id = 33 WHERE submitter_id = 172;
UPDATE ros_pl.tag_details SET tag_finder_id = 33 WHERE tag_finder_id = 172;
UPDATE ros_ps.observer_data SET creator_id = 33 WHERE creator_id = 172;
UPDATE ros_ps.observer_data SET submitter_id = 33 WHERE submitter_id = 172;
UPDATE ros_ps.tag_details SET tag_finder_id = 33 WHERE tag_finder_id = 172;
DELETE FROM ros_common.contact WHERE id = 172;
UPDATE ros_common.contact_role SET contact_id = 55 WHERE contact_id = 188;
UPDATE ros_common.observer SET contact_id = 55 WHERE contact_id = 188;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 55 WHERE fishing_master_id = 188;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 55 WHERE skipper_id = 188;
UPDATE ros_gn.observer_data SET creator_id = 55 WHERE creator_id = 188;
UPDATE ros_gn.observer_data SET submitter_id = 55 WHERE submitter_id = 188;
UPDATE ros_gn.tag_details SET tag_finder_id = 55 WHERE tag_finder_id = 188;
UPDATE ros_ll.observer_data SET creator_id = 55 WHERE creator_id = 188;
UPDATE ros_ll.observer_data SET submitter_id = 55 WHERE submitter_id = 188;
UPDATE ros_ll.tag_details SET tag_finder_id = 55 WHERE tag_finder_id = 188;
UPDATE ros_pl.observer_data SET creator_id = 55 WHERE creator_id = 188;
UPDATE ros_pl.observer_data SET submitter_id = 55 WHERE submitter_id = 188;
UPDATE ros_pl.tag_details SET tag_finder_id = 55 WHERE tag_finder_id = 188;
UPDATE ros_ps.observer_data SET creator_id = 55 WHERE creator_id = 188;
UPDATE ros_ps.observer_data SET submitter_id = 55 WHERE submitter_id = 188;
UPDATE ros_ps.tag_details SET tag_finder_id = 55 WHERE tag_finder_id = 188;
DELETE FROM ros_common.contact WHERE id = 188;
UPDATE ros_common.contact_role SET contact_id = 66 WHERE contact_id = 194;
UPDATE ros_common.observer SET contact_id = 66 WHERE contact_id = 194;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 66 WHERE fishing_master_id = 194;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 66 WHERE skipper_id = 194;
UPDATE ros_gn.observer_data SET creator_id = 66 WHERE creator_id = 194;
UPDATE ros_gn.observer_data SET submitter_id = 66 WHERE submitter_id = 194;
UPDATE ros_gn.tag_details SET tag_finder_id = 66 WHERE tag_finder_id = 194;
UPDATE ros_ll.observer_data SET creator_id = 66 WHERE creator_id = 194;
UPDATE ros_ll.observer_data SET submitter_id = 66 WHERE submitter_id = 194;
UPDATE ros_ll.tag_details SET tag_finder_id = 66 WHERE tag_finder_id = 194;
UPDATE ros_pl.observer_data SET creator_id = 66 WHERE creator_id = 194;
UPDATE ros_pl.observer_data SET submitter_id = 66 WHERE submitter_id = 194;
UPDATE ros_pl.tag_details SET tag_finder_id = 66 WHERE tag_finder_id = 194;
UPDATE ros_ps.observer_data SET creator_id = 66 WHERE creator_id = 194;
UPDATE ros_ps.observer_data SET submitter_id = 66 WHERE submitter_id = 194;
UPDATE ros_ps.tag_details SET tag_finder_id = 66 WHERE tag_finder_id = 194;
DELETE FROM ros_common.contact WHERE id = 194;
UPDATE ros_common.contact_role SET contact_id = 10 WHERE contact_id = 155;
UPDATE ros_common.observer SET contact_id = 10 WHERE contact_id = 155;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 10 WHERE fishing_master_id = 155;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 10 WHERE skipper_id = 155;
UPDATE ros_gn.observer_data SET creator_id = 10 WHERE creator_id = 155;
UPDATE ros_gn.observer_data SET submitter_id = 10 WHERE submitter_id = 155;
UPDATE ros_gn.tag_details SET tag_finder_id = 10 WHERE tag_finder_id = 155;
UPDATE ros_ll.observer_data SET creator_id = 10 WHERE creator_id = 155;
UPDATE ros_ll.observer_data SET submitter_id = 10 WHERE submitter_id = 155;
UPDATE ros_ll.tag_details SET tag_finder_id = 10 WHERE tag_finder_id = 155;
UPDATE ros_pl.observer_data SET creator_id = 10 WHERE creator_id = 155;
UPDATE ros_pl.observer_data SET submitter_id = 10 WHERE submitter_id = 155;
UPDATE ros_pl.tag_details SET tag_finder_id = 10 WHERE tag_finder_id = 155;
UPDATE ros_ps.observer_data SET creator_id = 10 WHERE creator_id = 155;
UPDATE ros_ps.observer_data SET submitter_id = 10 WHERE submitter_id = 155;
UPDATE ros_ps.tag_details SET tag_finder_id = 10 WHERE tag_finder_id = 155;
DELETE FROM ros_common.contact WHERE id = 155;
UPDATE ros_common.contact_role SET contact_id = 15 WHERE contact_id = 151;
UPDATE ros_common.observer SET contact_id = 15 WHERE contact_id = 151;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 15 WHERE fishing_master_id = 151;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 15 WHERE skipper_id = 151;
UPDATE ros_gn.observer_data SET creator_id = 15 WHERE creator_id = 151;
UPDATE ros_gn.observer_data SET submitter_id = 15 WHERE submitter_id = 151;
UPDATE ros_gn.tag_details SET tag_finder_id = 15 WHERE tag_finder_id = 151;
UPDATE ros_ll.observer_data SET creator_id = 15 WHERE creator_id = 151;
UPDATE ros_ll.observer_data SET submitter_id = 15 WHERE submitter_id = 151;
UPDATE ros_ll.tag_details SET tag_finder_id = 15 WHERE tag_finder_id = 151;
UPDATE ros_pl.observer_data SET creator_id = 15 WHERE creator_id = 151;
UPDATE ros_pl.observer_data SET submitter_id = 15 WHERE submitter_id = 151;
UPDATE ros_pl.tag_details SET tag_finder_id = 15 WHERE tag_finder_id = 151;
UPDATE ros_ps.observer_data SET creator_id = 15 WHERE creator_id = 151;
UPDATE ros_ps.observer_data SET submitter_id = 15 WHERE submitter_id = 151;
UPDATE ros_ps.tag_details SET tag_finder_id = 15 WHERE tag_finder_id = 151;
DELETE FROM ros_common.contact WHERE id = 151;
UPDATE ros_common.contact_role SET contact_id = 43 WHERE contact_id = 177;
UPDATE ros_common.observer SET contact_id = 43 WHERE contact_id = 177;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 43 WHERE fishing_master_id = 177;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 43 WHERE skipper_id = 177;
UPDATE ros_gn.observer_data SET creator_id = 43 WHERE creator_id = 177;
UPDATE ros_gn.observer_data SET submitter_id = 43 WHERE submitter_id = 177;
UPDATE ros_gn.tag_details SET tag_finder_id = 43 WHERE tag_finder_id = 177;
UPDATE ros_ll.observer_data SET creator_id = 43 WHERE creator_id = 177;
UPDATE ros_ll.observer_data SET submitter_id = 43 WHERE submitter_id = 177;
UPDATE ros_ll.tag_details SET tag_finder_id = 43 WHERE tag_finder_id = 177;
UPDATE ros_pl.observer_data SET creator_id = 43 WHERE creator_id = 177;
UPDATE ros_pl.observer_data SET submitter_id = 43 WHERE submitter_id = 177;
UPDATE ros_pl.tag_details SET tag_finder_id = 43 WHERE tag_finder_id = 177;
UPDATE ros_ps.observer_data SET creator_id = 43 WHERE creator_id = 177;
UPDATE ros_ps.observer_data SET submitter_id = 43 WHERE submitter_id = 177;
UPDATE ros_ps.tag_details SET tag_finder_id = 43 WHERE tag_finder_id = 177;
DELETE FROM ros_common.contact WHERE id = 177;
UPDATE ros_common.contact_role SET contact_id = 45 WHERE contact_id = 179;
UPDATE ros_common.observer SET contact_id = 45 WHERE contact_id = 179;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 45 WHERE fishing_master_id = 179;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 45 WHERE skipper_id = 179;
UPDATE ros_gn.observer_data SET creator_id = 45 WHERE creator_id = 179;
UPDATE ros_gn.observer_data SET submitter_id = 45 WHERE submitter_id = 179;
UPDATE ros_gn.tag_details SET tag_finder_id = 45 WHERE tag_finder_id = 179;
UPDATE ros_ll.observer_data SET creator_id = 45 WHERE creator_id = 179;
UPDATE ros_ll.observer_data SET submitter_id = 45 WHERE submitter_id = 179;
UPDATE ros_ll.tag_details SET tag_finder_id = 45 WHERE tag_finder_id = 179;
UPDATE ros_pl.observer_data SET creator_id = 45 WHERE creator_id = 179;
UPDATE ros_pl.observer_data SET submitter_id = 45 WHERE submitter_id = 179;
UPDATE ros_pl.tag_details SET tag_finder_id = 45 WHERE tag_finder_id = 179;
UPDATE ros_ps.observer_data SET creator_id = 45 WHERE creator_id = 179;
UPDATE ros_ps.observer_data SET submitter_id = 45 WHERE submitter_id = 179;
UPDATE ros_ps.tag_details SET tag_finder_id = 45 WHERE tag_finder_id = 179;
DELETE FROM ros_common.contact WHERE id = 179;
UPDATE ros_common.contact_role SET contact_id = 54 WHERE contact_id = 187;
UPDATE ros_common.observer SET contact_id = 54 WHERE contact_id = 187;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 54 WHERE fishing_master_id = 187;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 54 WHERE skipper_id = 187;
UPDATE ros_gn.observer_data SET creator_id = 54 WHERE creator_id = 187;
UPDATE ros_gn.observer_data SET submitter_id = 54 WHERE submitter_id = 187;
UPDATE ros_gn.tag_details SET tag_finder_id = 54 WHERE tag_finder_id = 187;
UPDATE ros_ll.observer_data SET creator_id = 54 WHERE creator_id = 187;
UPDATE ros_ll.observer_data SET submitter_id = 54 WHERE submitter_id = 187;
UPDATE ros_ll.tag_details SET tag_finder_id = 54 WHERE tag_finder_id = 187;
UPDATE ros_pl.observer_data SET creator_id = 54 WHERE creator_id = 187;
UPDATE ros_pl.observer_data SET submitter_id = 54 WHERE submitter_id = 187;
UPDATE ros_pl.tag_details SET tag_finder_id = 54 WHERE tag_finder_id = 187;
UPDATE ros_ps.observer_data SET creator_id = 54 WHERE creator_id = 187;
UPDATE ros_ps.observer_data SET submitter_id = 54 WHERE submitter_id = 187;
UPDATE ros_ps.tag_details SET tag_finder_id = 54 WHERE tag_finder_id = 187;
DELETE FROM ros_common.contact WHERE id = 187;
UPDATE ros_common.contact_role SET contact_id = 13 WHERE contact_id = 158;
UPDATE ros_common.observer SET contact_id = 13 WHERE contact_id = 158;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 13 WHERE fishing_master_id = 158;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 13 WHERE skipper_id = 158;
UPDATE ros_gn.observer_data SET creator_id = 13 WHERE creator_id = 158;
UPDATE ros_gn.observer_data SET submitter_id = 13 WHERE submitter_id = 158;
UPDATE ros_gn.tag_details SET tag_finder_id = 13 WHERE tag_finder_id = 158;
UPDATE ros_ll.observer_data SET creator_id = 13 WHERE creator_id = 158;
UPDATE ros_ll.observer_data SET submitter_id = 13 WHERE submitter_id = 158;
UPDATE ros_ll.tag_details SET tag_finder_id = 13 WHERE tag_finder_id = 158;
UPDATE ros_pl.observer_data SET creator_id = 13 WHERE creator_id = 158;
UPDATE ros_pl.observer_data SET submitter_id = 13 WHERE submitter_id = 158;
UPDATE ros_pl.tag_details SET tag_finder_id = 13 WHERE tag_finder_id = 158;
UPDATE ros_ps.observer_data SET creator_id = 13 WHERE creator_id = 158;
UPDATE ros_ps.observer_data SET submitter_id = 13 WHERE submitter_id = 158;
UPDATE ros_ps.tag_details SET tag_finder_id = 13 WHERE tag_finder_id = 158;
DELETE FROM ros_common.contact WHERE id = 158;
UPDATE ros_common.contact_role SET contact_id = 44 WHERE contact_id = 178;
UPDATE ros_common.observer SET contact_id = 44 WHERE contact_id = 178;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 44 WHERE fishing_master_id = 178;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 44 WHERE skipper_id = 178;
UPDATE ros_gn.observer_data SET creator_id = 44 WHERE creator_id = 178;
UPDATE ros_gn.observer_data SET submitter_id = 44 WHERE submitter_id = 178;
UPDATE ros_gn.tag_details SET tag_finder_id = 44 WHERE tag_finder_id = 178;
UPDATE ros_ll.observer_data SET creator_id = 44 WHERE creator_id = 178;
UPDATE ros_ll.observer_data SET submitter_id = 44 WHERE submitter_id = 178;
UPDATE ros_ll.tag_details SET tag_finder_id = 44 WHERE tag_finder_id = 178;
UPDATE ros_pl.observer_data SET creator_id = 44 WHERE creator_id = 178;
UPDATE ros_pl.observer_data SET submitter_id = 44 WHERE submitter_id = 178;
UPDATE ros_pl.tag_details SET tag_finder_id = 44 WHERE tag_finder_id = 178;
UPDATE ros_ps.observer_data SET creator_id = 44 WHERE creator_id = 178;
UPDATE ros_ps.observer_data SET submitter_id = 44 WHERE submitter_id = 178;
UPDATE ros_ps.tag_details SET tag_finder_id = 44 WHERE tag_finder_id = 178;
DELETE FROM ros_common.contact WHERE id = 178;
UPDATE ros_common.contact_role SET contact_id = 16 WHERE contact_id = 160;
UPDATE ros_common.observer SET contact_id = 16 WHERE contact_id = 160;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 16 WHERE fishing_master_id = 160;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 16 WHERE skipper_id = 160;
UPDATE ros_gn.observer_data SET creator_id = 16 WHERE creator_id = 160;
UPDATE ros_gn.observer_data SET submitter_id = 16 WHERE submitter_id = 160;
UPDATE ros_gn.tag_details SET tag_finder_id = 16 WHERE tag_finder_id = 160;
UPDATE ros_ll.observer_data SET creator_id = 16 WHERE creator_id = 160;
UPDATE ros_ll.observer_data SET submitter_id = 16 WHERE submitter_id = 160;
UPDATE ros_ll.tag_details SET tag_finder_id = 16 WHERE tag_finder_id = 160;
UPDATE ros_pl.observer_data SET creator_id = 16 WHERE creator_id = 160;
UPDATE ros_pl.observer_data SET submitter_id = 16 WHERE submitter_id = 160;
UPDATE ros_pl.tag_details SET tag_finder_id = 16 WHERE tag_finder_id = 160;
UPDATE ros_ps.observer_data SET creator_id = 16 WHERE creator_id = 160;
UPDATE ros_ps.observer_data SET submitter_id = 16 WHERE submitter_id = 160;
UPDATE ros_ps.tag_details SET tag_finder_id = 16 WHERE tag_finder_id = 160;
DELETE FROM ros_common.contact WHERE id = 160;
UPDATE ros_common.contact_role SET contact_id = 71 WHERE contact_id = 143;
UPDATE ros_common.observer SET contact_id = 71 WHERE contact_id = 143;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 71 WHERE fishing_master_id = 143;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 71 WHERE skipper_id = 143;
UPDATE ros_gn.observer_data SET creator_id = 71 WHERE creator_id = 143;
UPDATE ros_gn.observer_data SET submitter_id = 71 WHERE submitter_id = 143;
UPDATE ros_gn.tag_details SET tag_finder_id = 71 WHERE tag_finder_id = 143;
UPDATE ros_ll.observer_data SET creator_id = 71 WHERE creator_id = 143;
UPDATE ros_ll.observer_data SET submitter_id = 71 WHERE submitter_id = 143;
UPDATE ros_ll.tag_details SET tag_finder_id = 71 WHERE tag_finder_id = 143;
UPDATE ros_pl.observer_data SET creator_id = 71 WHERE creator_id = 143;
UPDATE ros_pl.observer_data SET submitter_id = 71 WHERE submitter_id = 143;
UPDATE ros_pl.tag_details SET tag_finder_id = 71 WHERE tag_finder_id = 143;
UPDATE ros_ps.observer_data SET creator_id = 71 WHERE creator_id = 143;
UPDATE ros_ps.observer_data SET submitter_id = 71 WHERE submitter_id = 143;
UPDATE ros_ps.tag_details SET tag_finder_id = 71 WHERE tag_finder_id = 143;
DELETE FROM ros_common.contact WHERE id = 143;
-- UPDATE ros_common.contact_role SET contact_id = 71 WHERE contact_id = 197;
DELETE FROM ros_common.contact_role  WHERE contact_id = 197;
UPDATE ros_common.observer SET contact_id = 71 WHERE contact_id = 197;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 71 WHERE fishing_master_id = 197;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 71 WHERE skipper_id = 197;
UPDATE ros_gn.observer_data SET creator_id = 71 WHERE creator_id = 197;
UPDATE ros_gn.observer_data SET submitter_id = 71 WHERE submitter_id = 197;
UPDATE ros_gn.tag_details SET tag_finder_id = 71 WHERE tag_finder_id = 197;
UPDATE ros_ll.observer_data SET creator_id = 71 WHERE creator_id = 197;
UPDATE ros_ll.observer_data SET submitter_id = 71 WHERE submitter_id = 197;
UPDATE ros_ll.tag_details SET tag_finder_id = 71 WHERE tag_finder_id = 197;
UPDATE ros_pl.observer_data SET creator_id = 71 WHERE creator_id = 197;
UPDATE ros_pl.observer_data SET submitter_id = 71 WHERE submitter_id = 197;
UPDATE ros_pl.tag_details SET tag_finder_id = 71 WHERE tag_finder_id = 197;
UPDATE ros_ps.observer_data SET creator_id = 71 WHERE creator_id = 197;
UPDATE ros_ps.observer_data SET submitter_id = 71 WHERE submitter_id = 197;
UPDATE ros_ps.tag_details SET tag_finder_id = 71 WHERE tag_finder_id = 197;
DELETE FROM ros_common.contact WHERE id = 197;
UPDATE ros_common.contact_role SET contact_id = 50 WHERE contact_id = 181;
UPDATE ros_common.observer SET contact_id = 50 WHERE contact_id = 181;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 50 WHERE fishing_master_id = 181;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 50 WHERE skipper_id = 181;
UPDATE ros_gn.observer_data SET creator_id = 50 WHERE creator_id = 181;
UPDATE ros_gn.observer_data SET submitter_id = 50 WHERE submitter_id = 181;
UPDATE ros_gn.tag_details SET tag_finder_id = 50 WHERE tag_finder_id = 181;
UPDATE ros_ll.observer_data SET creator_id = 50 WHERE creator_id = 181;
UPDATE ros_ll.observer_data SET submitter_id = 50 WHERE submitter_id = 181;
UPDATE ros_ll.tag_details SET tag_finder_id = 50 WHERE tag_finder_id = 181;
UPDATE ros_pl.observer_data SET creator_id = 50 WHERE creator_id = 181;
UPDATE ros_pl.observer_data SET submitter_id = 50 WHERE submitter_id = 181;
UPDATE ros_pl.tag_details SET tag_finder_id = 50 WHERE tag_finder_id = 181;
UPDATE ros_ps.observer_data SET creator_id = 50 WHERE creator_id = 181;
UPDATE ros_ps.observer_data SET submitter_id = 50 WHERE submitter_id = 181;
UPDATE ros_ps.tag_details SET tag_finder_id = 50 WHERE tag_finder_id = 181;
DELETE FROM ros_common.contact WHERE id = 181;
UPDATE ros_common.contact_role SET contact_id = 18 WHERE contact_id = 161;
UPDATE ros_common.observer SET contact_id = 18 WHERE contact_id = 161;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 18 WHERE fishing_master_id = 161;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 18 WHERE skipper_id = 161;
UPDATE ros_gn.observer_data SET creator_id = 18 WHERE creator_id = 161;
UPDATE ros_gn.observer_data SET submitter_id = 18 WHERE submitter_id = 161;
UPDATE ros_gn.tag_details SET tag_finder_id = 18 WHERE tag_finder_id = 161;
UPDATE ros_ll.observer_data SET creator_id = 18 WHERE creator_id = 161;
UPDATE ros_ll.observer_data SET submitter_id = 18 WHERE submitter_id = 161;
UPDATE ros_ll.tag_details SET tag_finder_id = 18 WHERE tag_finder_id = 161;
UPDATE ros_pl.observer_data SET creator_id = 18 WHERE creator_id = 161;
UPDATE ros_pl.observer_data SET submitter_id = 18 WHERE submitter_id = 161;
UPDATE ros_pl.tag_details SET tag_finder_id = 18 WHERE tag_finder_id = 161;
UPDATE ros_ps.observer_data SET creator_id = 18 WHERE creator_id = 161;
UPDATE ros_ps.observer_data SET submitter_id = 18 WHERE submitter_id = 161;
UPDATE ros_ps.tag_details SET tag_finder_id = 18 WHERE tag_finder_id = 161;
DELETE FROM ros_common.contact WHERE id = 161;
UPDATE ros_common.contact_role SET contact_id = 28 WHERE contact_id = 142;
UPDATE ros_common.observer SET contact_id = 28 WHERE contact_id = 142;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 28 WHERE fishing_master_id = 142;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 28 WHERE skipper_id = 142;
UPDATE ros_gn.observer_data SET creator_id = 28 WHERE creator_id = 142;
UPDATE ros_gn.observer_data SET submitter_id = 28 WHERE submitter_id = 142;
UPDATE ros_gn.tag_details SET tag_finder_id = 28 WHERE tag_finder_id = 142;
UPDATE ros_ll.observer_data SET creator_id = 28 WHERE creator_id = 142;
UPDATE ros_ll.observer_data SET submitter_id = 28 WHERE submitter_id = 142;
UPDATE ros_ll.tag_details SET tag_finder_id = 28 WHERE tag_finder_id = 142;
UPDATE ros_pl.observer_data SET creator_id = 28 WHERE creator_id = 142;
UPDATE ros_pl.observer_data SET submitter_id = 28 WHERE submitter_id = 142;
UPDATE ros_pl.tag_details SET tag_finder_id = 28 WHERE tag_finder_id = 142;
UPDATE ros_ps.observer_data SET creator_id = 28 WHERE creator_id = 142;
UPDATE ros_ps.observer_data SET submitter_id = 28 WHERE submitter_id = 142;
UPDATE ros_ps.tag_details SET tag_finder_id = 28 WHERE tag_finder_id = 142;
DELETE FROM ros_common.contact WHERE id = 142;
UPDATE ros_common.contact_role SET contact_id = 12 WHERE contact_id = 157;
UPDATE ros_common.observer SET contact_id = 12 WHERE contact_id = 157;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 12 WHERE fishing_master_id = 157;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 12 WHERE skipper_id = 157;
UPDATE ros_gn.observer_data SET creator_id = 12 WHERE creator_id = 157;
UPDATE ros_gn.observer_data SET submitter_id = 12 WHERE submitter_id = 157;
UPDATE ros_gn.tag_details SET tag_finder_id = 12 WHERE tag_finder_id = 157;
UPDATE ros_ll.observer_data SET creator_id = 12 WHERE creator_id = 157;
UPDATE ros_ll.observer_data SET submitter_id = 12 WHERE submitter_id = 157;
UPDATE ros_ll.tag_details SET tag_finder_id = 12 WHERE tag_finder_id = 157;
UPDATE ros_pl.observer_data SET creator_id = 12 WHERE creator_id = 157;
UPDATE ros_pl.observer_data SET submitter_id = 12 WHERE submitter_id = 157;
UPDATE ros_pl.tag_details SET tag_finder_id = 12 WHERE tag_finder_id = 157;
UPDATE ros_ps.observer_data SET creator_id = 12 WHERE creator_id = 157;
UPDATE ros_ps.observer_data SET submitter_id = 12 WHERE submitter_id = 157;
UPDATE ros_ps.tag_details SET tag_finder_id = 12 WHERE tag_finder_id = 157;
DELETE FROM ros_common.contact WHERE id = 157;
UPDATE ros_common.contact_role SET contact_id = 14 WHERE contact_id = 159;
UPDATE ros_common.observer SET contact_id = 14 WHERE contact_id = 159;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 14 WHERE fishing_master_id = 159;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 14 WHERE skipper_id = 159;
UPDATE ros_gn.observer_data SET creator_id = 14 WHERE creator_id = 159;
UPDATE ros_gn.observer_data SET submitter_id = 14 WHERE submitter_id = 159;
UPDATE ros_gn.tag_details SET tag_finder_id = 14 WHERE tag_finder_id = 159;
UPDATE ros_ll.observer_data SET creator_id = 14 WHERE creator_id = 159;
UPDATE ros_ll.observer_data SET submitter_id = 14 WHERE submitter_id = 159;
UPDATE ros_ll.tag_details SET tag_finder_id = 14 WHERE tag_finder_id = 159;
UPDATE ros_pl.observer_data SET creator_id = 14 WHERE creator_id = 159;
UPDATE ros_pl.observer_data SET submitter_id = 14 WHERE submitter_id = 159;
UPDATE ros_pl.tag_details SET tag_finder_id = 14 WHERE tag_finder_id = 159;
UPDATE ros_ps.observer_data SET creator_id = 14 WHERE creator_id = 159;
UPDATE ros_ps.observer_data SET submitter_id = 14 WHERE submitter_id = 159;
UPDATE ros_ps.tag_details SET tag_finder_id = 14 WHERE tag_finder_id = 159;
DELETE FROM ros_common.contact WHERE id = 159;
UPDATE ros_common.contact_role SET contact_id = 39 WHERE contact_id = 175;
UPDATE ros_common.observer SET contact_id = 39 WHERE contact_id = 175;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 39 WHERE fishing_master_id = 175;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 39 WHERE skipper_id = 175;
UPDATE ros_gn.observer_data SET creator_id = 39 WHERE creator_id = 175;
UPDATE ros_gn.observer_data SET submitter_id = 39 WHERE submitter_id = 175;
UPDATE ros_gn.tag_details SET tag_finder_id = 39 WHERE tag_finder_id = 175;
UPDATE ros_ll.observer_data SET creator_id = 39 WHERE creator_id = 175;
UPDATE ros_ll.observer_data SET submitter_id = 39 WHERE submitter_id = 175;
UPDATE ros_ll.tag_details SET tag_finder_id = 39 WHERE tag_finder_id = 175;
UPDATE ros_pl.observer_data SET creator_id = 39 WHERE creator_id = 175;
UPDATE ros_pl.observer_data SET submitter_id = 39 WHERE submitter_id = 175;
UPDATE ros_pl.tag_details SET tag_finder_id = 39 WHERE tag_finder_id = 175;
UPDATE ros_ps.observer_data SET creator_id = 39 WHERE creator_id = 175;
UPDATE ros_ps.observer_data SET submitter_id = 39 WHERE submitter_id = 175;
UPDATE ros_ps.tag_details SET tag_finder_id = 39 WHERE tag_finder_id = 175;
DELETE FROM ros_common.contact WHERE id = 175;
UPDATE ros_common.contact_role SET contact_id = 38 WHERE contact_id = 174;
UPDATE ros_common.observer SET contact_id = 38 WHERE contact_id = 174;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 38 WHERE fishing_master_id = 174;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 38 WHERE skipper_id = 174;
UPDATE ros_gn.observer_data SET creator_id = 38 WHERE creator_id = 174;
UPDATE ros_gn.observer_data SET submitter_id = 38 WHERE submitter_id = 174;
UPDATE ros_gn.tag_details SET tag_finder_id = 38 WHERE tag_finder_id = 174;
UPDATE ros_ll.observer_data SET creator_id = 38 WHERE creator_id = 174;
UPDATE ros_ll.observer_data SET submitter_id = 38 WHERE submitter_id = 174;
UPDATE ros_ll.tag_details SET tag_finder_id = 38 WHERE tag_finder_id = 174;
UPDATE ros_pl.observer_data SET creator_id = 38 WHERE creator_id = 174;
UPDATE ros_pl.observer_data SET submitter_id = 38 WHERE submitter_id = 174;
UPDATE ros_pl.tag_details SET tag_finder_id = 38 WHERE tag_finder_id = 174;
UPDATE ros_ps.observer_data SET creator_id = 38 WHERE creator_id = 174;
UPDATE ros_ps.observer_data SET submitter_id = 38 WHERE submitter_id = 174;
UPDATE ros_ps.tag_details SET tag_finder_id = 38 WHERE tag_finder_id = 174;
DELETE FROM ros_common.contact WHERE id = 174;
UPDATE ros_common.contact_role SET contact_id = 22 WHERE contact_id = 164;
UPDATE ros_common.observer SET contact_id = 22 WHERE contact_id = 164;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 22 WHERE fishing_master_id = 164;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 22 WHERE skipper_id = 164;
UPDATE ros_gn.observer_data SET creator_id = 22 WHERE creator_id = 164;
UPDATE ros_gn.observer_data SET submitter_id = 22 WHERE submitter_id = 164;
UPDATE ros_gn.tag_details SET tag_finder_id = 22 WHERE tag_finder_id = 164;
UPDATE ros_ll.observer_data SET creator_id = 22 WHERE creator_id = 164;
UPDATE ros_ll.observer_data SET submitter_id = 22 WHERE submitter_id = 164;
UPDATE ros_ll.tag_details SET tag_finder_id = 22 WHERE tag_finder_id = 164;
UPDATE ros_pl.observer_data SET creator_id = 22 WHERE creator_id = 164;
UPDATE ros_pl.observer_data SET submitter_id = 22 WHERE submitter_id = 164;
UPDATE ros_pl.tag_details SET tag_finder_id = 22 WHERE tag_finder_id = 164;
UPDATE ros_ps.observer_data SET creator_id = 22 WHERE creator_id = 164;
UPDATE ros_ps.observer_data SET submitter_id = 22 WHERE submitter_id = 164;
UPDATE ros_ps.tag_details SET tag_finder_id = 22 WHERE tag_finder_id = 164;
DELETE FROM ros_common.contact WHERE id = 164;
UPDATE ros_common.contact_role SET contact_id = 24 WHERE contact_id = 166;
UPDATE ros_common.observer SET contact_id = 24 WHERE contact_id = 166;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 24 WHERE fishing_master_id = 166;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 24 WHERE skipper_id = 166;
UPDATE ros_gn.observer_data SET creator_id = 24 WHERE creator_id = 166;
UPDATE ros_gn.observer_data SET submitter_id = 24 WHERE submitter_id = 166;
UPDATE ros_gn.tag_details SET tag_finder_id = 24 WHERE tag_finder_id = 166;
UPDATE ros_ll.observer_data SET creator_id = 24 WHERE creator_id = 166;
UPDATE ros_ll.observer_data SET submitter_id = 24 WHERE submitter_id = 166;
UPDATE ros_ll.tag_details SET tag_finder_id = 24 WHERE tag_finder_id = 166;
UPDATE ros_pl.observer_data SET creator_id = 24 WHERE creator_id = 166;
UPDATE ros_pl.observer_data SET submitter_id = 24 WHERE submitter_id = 166;
UPDATE ros_pl.tag_details SET tag_finder_id = 24 WHERE tag_finder_id = 166;
UPDATE ros_ps.observer_data SET creator_id = 24 WHERE creator_id = 166;
UPDATE ros_ps.observer_data SET submitter_id = 24 WHERE submitter_id = 166;
UPDATE ros_ps.tag_details SET tag_finder_id = 24 WHERE tag_finder_id = 166;
DELETE FROM ros_common.contact WHERE id = 166;
UPDATE ros_common.contact_role SET contact_id = 17 WHERE contact_id = 161;
UPDATE ros_common.observer SET contact_id = 17 WHERE contact_id = 161;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 17 WHERE fishing_master_id = 161;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 17 WHERE skipper_id = 161;
UPDATE ros_gn.observer_data SET creator_id = 17 WHERE creator_id = 161;
UPDATE ros_gn.observer_data SET submitter_id = 17 WHERE submitter_id = 161;
UPDATE ros_gn.tag_details SET tag_finder_id = 17 WHERE tag_finder_id = 161;
UPDATE ros_ll.observer_data SET creator_id = 17 WHERE creator_id = 161;
UPDATE ros_ll.observer_data SET submitter_id = 17 WHERE submitter_id = 161;
UPDATE ros_ll.tag_details SET tag_finder_id = 17 WHERE tag_finder_id = 161;
UPDATE ros_pl.observer_data SET creator_id = 17 WHERE creator_id = 161;
UPDATE ros_pl.observer_data SET submitter_id = 17 WHERE submitter_id = 161;
UPDATE ros_pl.tag_details SET tag_finder_id = 17 WHERE tag_finder_id = 161;
UPDATE ros_ps.observer_data SET creator_id = 17 WHERE creator_id = 161;
UPDATE ros_ps.observer_data SET submitter_id = 17 WHERE submitter_id = 161;
UPDATE ros_ps.tag_details SET tag_finder_id = 17 WHERE tag_finder_id = 161;
DELETE FROM ros_common.contact WHERE id = 161;
UPDATE ros_common.contact_role SET contact_id = 35 WHERE contact_id = 153;
UPDATE ros_common.observer SET contact_id = 35 WHERE contact_id = 153;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 35 WHERE fishing_master_id = 153;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 35 WHERE skipper_id = 153;
UPDATE ros_gn.observer_data SET creator_id = 35 WHERE creator_id = 153;
UPDATE ros_gn.observer_data SET submitter_id = 35 WHERE submitter_id = 153;
UPDATE ros_gn.tag_details SET tag_finder_id = 35 WHERE tag_finder_id = 153;
UPDATE ros_ll.observer_data SET creator_id = 35 WHERE creator_id = 153;
UPDATE ros_ll.observer_data SET submitter_id = 35 WHERE submitter_id = 153;
UPDATE ros_ll.tag_details SET tag_finder_id = 35 WHERE tag_finder_id = 153;
UPDATE ros_pl.observer_data SET creator_id = 35 WHERE creator_id = 153;
UPDATE ros_pl.observer_data SET submitter_id = 35 WHERE submitter_id = 153;
UPDATE ros_pl.tag_details SET tag_finder_id = 35 WHERE tag_finder_id = 153;
UPDATE ros_ps.observer_data SET creator_id = 35 WHERE creator_id = 153;
UPDATE ros_ps.observer_data SET submitter_id = 35 WHERE submitter_id = 153;
UPDATE ros_ps.tag_details SET tag_finder_id = 35 WHERE tag_finder_id = 153;
DELETE FROM ros_common.contact WHERE id = 153;
UPDATE ros_common.contact_role SET contact_id = 53 WHERE contact_id = 186;
UPDATE ros_common.observer SET contact_id = 53 WHERE contact_id = 186;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 53 WHERE fishing_master_id = 186;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 53 WHERE skipper_id = 186;
UPDATE ros_gn.observer_data SET creator_id = 53 WHERE creator_id = 186;
UPDATE ros_gn.observer_data SET submitter_id = 53 WHERE submitter_id = 186;
UPDATE ros_gn.tag_details SET tag_finder_id = 53 WHERE tag_finder_id = 186;
UPDATE ros_ll.observer_data SET creator_id = 53 WHERE creator_id = 186;
UPDATE ros_ll.observer_data SET submitter_id = 53 WHERE submitter_id = 186;
UPDATE ros_ll.tag_details SET tag_finder_id = 53 WHERE tag_finder_id = 186;
UPDATE ros_pl.observer_data SET creator_id = 53 WHERE creator_id = 186;
UPDATE ros_pl.observer_data SET submitter_id = 53 WHERE submitter_id = 186;
UPDATE ros_pl.tag_details SET tag_finder_id = 53 WHERE tag_finder_id = 186;
UPDATE ros_ps.observer_data SET creator_id = 53 WHERE creator_id = 186;
UPDATE ros_ps.observer_data SET submitter_id = 53 WHERE submitter_id = 186;
UPDATE ros_ps.tag_details SET tag_finder_id = 53 WHERE tag_finder_id = 186;
DELETE FROM ros_common.contact WHERE id = 186;
UPDATE ros_common.contact_role SET contact_id = 36 WHERE contact_id = 144;
UPDATE ros_common.observer SET contact_id = 36 WHERE contact_id = 144;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 36 WHERE fishing_master_id = 144;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 36 WHERE skipper_id = 144;
UPDATE ros_gn.observer_data SET creator_id = 36 WHERE creator_id = 144;
UPDATE ros_gn.observer_data SET submitter_id = 36 WHERE submitter_id = 144;
UPDATE ros_gn.tag_details SET tag_finder_id = 36 WHERE tag_finder_id = 144;
UPDATE ros_ll.observer_data SET creator_id = 36 WHERE creator_id = 144;
UPDATE ros_ll.observer_data SET submitter_id = 36 WHERE submitter_id = 144;
UPDATE ros_ll.tag_details SET tag_finder_id = 36 WHERE tag_finder_id = 144;
UPDATE ros_pl.observer_data SET creator_id = 36 WHERE creator_id = 144;
UPDATE ros_pl.observer_data SET submitter_id = 36 WHERE submitter_id = 144;
UPDATE ros_pl.tag_details SET tag_finder_id = 36 WHERE tag_finder_id = 144;
UPDATE ros_ps.observer_data SET creator_id = 36 WHERE creator_id = 144;
UPDATE ros_ps.observer_data SET submitter_id = 36 WHERE submitter_id = 144;
UPDATE ros_ps.tag_details SET tag_finder_id = 36 WHERE tag_finder_id = 144;
DELETE FROM ros_common.contact WHERE id = 144;
UPDATE ros_common.contact_role SET contact_id = 26 WHERE contact_id = 149;
UPDATE ros_common.observer SET contact_id = 26 WHERE contact_id = 149;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 26 WHERE fishing_master_id = 149;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 26 WHERE skipper_id = 149;
UPDATE ros_gn.observer_data SET creator_id = 26 WHERE creator_id = 149;
UPDATE ros_gn.observer_data SET submitter_id = 26 WHERE submitter_id = 149;
UPDATE ros_gn.tag_details SET tag_finder_id = 26 WHERE tag_finder_id = 149;
UPDATE ros_ll.observer_data SET creator_id = 26 WHERE creator_id = 149;
UPDATE ros_ll.observer_data SET submitter_id = 26 WHERE submitter_id = 149;
UPDATE ros_ll.tag_details SET tag_finder_id = 26 WHERE tag_finder_id = 149;
UPDATE ros_pl.observer_data SET creator_id = 26 WHERE creator_id = 149;
UPDATE ros_pl.observer_data SET submitter_id = 26 WHERE submitter_id = 149;
UPDATE ros_pl.tag_details SET tag_finder_id = 26 WHERE tag_finder_id = 149;
UPDATE ros_ps.observer_data SET creator_id = 26 WHERE creator_id = 149;
UPDATE ros_ps.observer_data SET submitter_id = 26 WHERE submitter_id = 149;
UPDATE ros_ps.tag_details SET tag_finder_id = 26 WHERE tag_finder_id = 149;
DELETE FROM ros_common.contact WHERE id = 149;
UPDATE ros_common.contact_role SET contact_id = 46 WHERE contact_id = 180;
UPDATE ros_common.observer SET contact_id = 46 WHERE contact_id = 180;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 46 WHERE fishing_master_id = 180;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 46 WHERE skipper_id = 180;
UPDATE ros_gn.observer_data SET creator_id = 46 WHERE creator_id = 180;
UPDATE ros_gn.observer_data SET submitter_id = 46 WHERE submitter_id = 180;
UPDATE ros_gn.tag_details SET tag_finder_id = 46 WHERE tag_finder_id = 180;
UPDATE ros_ll.observer_data SET creator_id = 46 WHERE creator_id = 180;
UPDATE ros_ll.observer_data SET submitter_id = 46 WHERE submitter_id = 180;
UPDATE ros_ll.tag_details SET tag_finder_id = 46 WHERE tag_finder_id = 180;
UPDATE ros_pl.observer_data SET creator_id = 46 WHERE creator_id = 180;
UPDATE ros_pl.observer_data SET submitter_id = 46 WHERE submitter_id = 180;
UPDATE ros_pl.tag_details SET tag_finder_id = 46 WHERE tag_finder_id = 180;
UPDATE ros_ps.observer_data SET creator_id = 46 WHERE creator_id = 180;
UPDATE ros_ps.observer_data SET submitter_id = 46 WHERE submitter_id = 180;
UPDATE ros_ps.tag_details SET tag_finder_id = 46 WHERE tag_finder_id = 180;
DELETE FROM ros_common.contact WHERE id = 180;
UPDATE ros_common.contact_role SET contact_id = 41 WHERE contact_id = 176;
UPDATE ros_common.observer SET contact_id = 41 WHERE contact_id = 176;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 41 WHERE fishing_master_id = 176;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 41 WHERE skipper_id = 176;
UPDATE ros_gn.observer_data SET creator_id = 41 WHERE creator_id = 176;
UPDATE ros_gn.observer_data SET submitter_id = 41 WHERE submitter_id = 176;
UPDATE ros_gn.tag_details SET tag_finder_id = 41 WHERE tag_finder_id = 176;
UPDATE ros_ll.observer_data SET creator_id = 41 WHERE creator_id = 176;
UPDATE ros_ll.observer_data SET submitter_id = 41 WHERE submitter_id = 176;
UPDATE ros_ll.tag_details SET tag_finder_id = 41 WHERE tag_finder_id = 176;
UPDATE ros_pl.observer_data SET creator_id = 41 WHERE creator_id = 176;
UPDATE ros_pl.observer_data SET submitter_id = 41 WHERE submitter_id = 176;
UPDATE ros_pl.tag_details SET tag_finder_id = 41 WHERE tag_finder_id = 176;
UPDATE ros_ps.observer_data SET creator_id = 41 WHERE creator_id = 176;
UPDATE ros_ps.observer_data SET submitter_id = 41 WHERE submitter_id = 176;
UPDATE ros_ps.tag_details SET tag_finder_id = 41 WHERE tag_finder_id = 176;
DELETE FROM ros_common.contact WHERE id = 176;
UPDATE ros_common.contact_role SET contact_id = 75 WHERE contact_id = 198;
UPDATE ros_common.observer SET contact_id = 75 WHERE contact_id = 198;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 75 WHERE fishing_master_id = 198;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 75 WHERE skipper_id = 198;
UPDATE ros_gn.observer_data SET creator_id = 75 WHERE creator_id = 198;
UPDATE ros_gn.observer_data SET submitter_id = 75 WHERE submitter_id = 198;
UPDATE ros_gn.tag_details SET tag_finder_id = 75 WHERE tag_finder_id = 198;
UPDATE ros_ll.observer_data SET creator_id = 75 WHERE creator_id = 198;
UPDATE ros_ll.observer_data SET submitter_id = 75 WHERE submitter_id = 198;
UPDATE ros_ll.tag_details SET tag_finder_id = 75 WHERE tag_finder_id = 198;
UPDATE ros_pl.observer_data SET creator_id = 75 WHERE creator_id = 198;
UPDATE ros_pl.observer_data SET submitter_id = 75 WHERE submitter_id = 198;
UPDATE ros_pl.tag_details SET tag_finder_id = 75 WHERE tag_finder_id = 198;
UPDATE ros_ps.observer_data SET creator_id = 75 WHERE creator_id = 198;
UPDATE ros_ps.observer_data SET submitter_id = 75 WHERE submitter_id = 198;
UPDATE ros_ps.tag_details SET tag_finder_id = 75 WHERE tag_finder_id = 198;
DELETE FROM ros_common.contact WHERE id = 198;

-- UPDATE ros_common.contact_role SET contact_id = 18 WHERE contact_id = 162;
DELETE FROM ros_common.contact_role WHERE contact_id = 162;
-- UPDATE ros_common.observer SET contact_id = 18 WHERE contact_id = 162;
DELETE FROM  ros_common.observer  WHERE contact_id = 162;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 18 WHERE fishing_master_id = 162;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 18 WHERE skipper_id = 162;
UPDATE ros_gn.observer_data SET creator_id = 18 WHERE creator_id = 162;
UPDATE ros_gn.observer_data SET submitter_id = 18 WHERE submitter_id = 162;
UPDATE ros_gn.tag_details SET tag_finder_id = 18 WHERE tag_finder_id = 162;
UPDATE ros_ll.observer_data SET creator_id = 18 WHERE creator_id = 162;
UPDATE ros_ll.observer_data SET submitter_id = 18 WHERE submitter_id = 162;
UPDATE ros_ll.tag_details SET tag_finder_id = 18 WHERE tag_finder_id = 162;
UPDATE ros_pl.observer_data SET creator_id = 18 WHERE creator_id = 162;
UPDATE ros_pl.observer_data SET submitter_id = 18 WHERE submitter_id = 162;
UPDATE ros_pl.tag_details SET tag_finder_id = 18 WHERE tag_finder_id = 162;
UPDATE ros_ps.observer_data SET creator_id = 18 WHERE creator_id = 162;
UPDATE ros_ps.observer_data SET submitter_id = 18 WHERE submitter_id = 162;
UPDATE ros_ps.tag_details SET tag_finder_id = 18 WHERE tag_finder_id = 162;
DELETE FROM ros_common.contact WHERE id = 162;

UPDATE ros_common.contact_role SET contact_id = 23 WHERE contact_id = 165;
UPDATE ros_common.observer SET contact_id = 23 WHERE contact_id = 165;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 23 WHERE fishing_master_id = 165;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 23 WHERE skipper_id = 165;
UPDATE ros_gn.observer_data SET creator_id = 23 WHERE creator_id = 165;
UPDATE ros_gn.observer_data SET submitter_id = 23 WHERE submitter_id = 165;
UPDATE ros_gn.tag_details SET tag_finder_id = 23 WHERE tag_finder_id = 165;
UPDATE ros_ll.observer_data SET creator_id = 23 WHERE creator_id = 165;
UPDATE ros_ll.observer_data SET submitter_id = 23 WHERE submitter_id = 165;
UPDATE ros_ll.tag_details SET tag_finder_id = 23 WHERE tag_finder_id = 165;
UPDATE ros_pl.observer_data SET creator_id = 23 WHERE creator_id = 165;
UPDATE ros_pl.observer_data SET submitter_id = 23 WHERE submitter_id = 165;
UPDATE ros_pl.tag_details SET tag_finder_id = 23 WHERE tag_finder_id = 165;
UPDATE ros_ps.observer_data SET creator_id = 23 WHERE creator_id = 165;
UPDATE ros_ps.observer_data SET submitter_id = 23 WHERE submitter_id = 165;
UPDATE ros_ps.tag_details SET tag_finder_id = 23 WHERE tag_finder_id = 165;
DELETE FROM ros_common.contact WHERE id = 165;

CREATE OR REPLACE FUNCTION unaccent_string(text)
RETURNS text
IMMUTABLE
STRICT
LANGUAGE SQL
AS $$
SELECT translate(
    $1,
    'ÇçâãäåāăąÁÂÃÄÅĀĂĄèééêëēĕėęěĒĔĖĘĚìíîïìĩīĭÌÍÎÏÌĨĪĬóôõöōŏőÒÓÔÕÖŌŎŐùúûüũūŭůÙÚÛÜŨŪŬŮ',
    'ccaaaaaaaaaaaaaaaeeeeeeeeeeeeeeeiiiiiiiiiiiiiiiiooooooooooooooouuuuuuuuuuuuuuuu'
);
$$;

UPDATE ros_common.contact SET full_name = upper(unaccent_string(full_name));

DROP FUNCTION unaccent_string(text);

DROP VIEW ros_common.contact_with_observer;
CREATE OR REPLACE VIEW ros_common.contact_with_observer AS
    SELECT t.id, t.full_name , o.iotc_observer_identifier, t.nationality_code, t.active, t.email, t.phone
    FROM ros_common.contact t
             JOIN ros_common.observer o ON t.id = o.contact_id
    ORDER BY full_name;

ALTER TABLE ros_common.contact ALTER COLUMN id DROP IDENTITY;
-- remove 16 foreign key(s) from ros_common.contact→id
-- remove the foreign key for ros_common.contact_role→contact_id:fk_ros_common_contact_contact_role
ALTER TABLE ros_common.contact_role DROP CONSTRAINT fk_ros_common_contact_contact_role;
-- remove the foreign key for ros_common.observer→contact_id:fk_ros_common_contact_id_observer
ALTER TABLE ros_common.observer DROP CONSTRAINT fk_ros_common_contact_id_observer;
-- remove the foreign key for ros_common.vessel_owner_and_personnel→fishing_master_id:vsslwnrndprsfshngmstrd
ALTER TABLE ros_common.vessel_owner_and_personnel DROP CONSTRAINT vsslwnrndprsfshngmstrd;
-- remove the foreign key for ros_common.vessel_owner_and_personnel→skipper_id:vsslwnrndprsnnelskpprd
ALTER TABLE ros_common.vessel_owner_and_personnel DROP CONSTRAINT vsslwnrndprsnnelskpprd;
-- remove the foreign key for ros_gn.observer_data→creator_id:gnbserverdatacreatorid
ALTER TABLE ros_gn.observer_data DROP CONSTRAINT gnbserverdatacreatorid;
-- remove the foreign key for ros_gn.observer_data→submitter_id:gnbserverdatasbmtterid
ALTER TABLE ros_gn.observer_data DROP CONSTRAINT gnbserverdatasbmtterid;
-- remove the foreign key for ros_gn.tag_details→tag_finder_id:gntagdetailstgfinderid
ALTER TABLE ros_gn.tag_details DROP CONSTRAINT gntagdetailstgfinderid;
-- remove the foreign key for ros_ll.observer_data→creator_id:llbserverdatacreatorid
ALTER TABLE ros_ll.observer_data DROP CONSTRAINT llbserverdatacreatorid;
-- remove the foreign key for ros_ll.observer_data→submitter_id:llbserverdatasbmtterid
ALTER TABLE ros_ll.observer_data DROP CONSTRAINT llbserverdatasbmtterid;
-- remove the foreign key for ros_ll.tag_details→tag_finder_id:lltagdetailstgfinderid
ALTER TABLE ros_ll.tag_details DROP CONSTRAINT lltagdetailstgfinderid;
-- remove the foreign key for ros_pl.observer_data→creator_id:plbserverdatacreatorid
ALTER TABLE ros_pl.observer_data DROP CONSTRAINT plbserverdatacreatorid;
-- remove the foreign key for ros_pl.observer_data→submitter_id:plbserverdatasbmtterid
ALTER TABLE ros_pl.observer_data DROP CONSTRAINT plbserverdatasbmtterid;
-- remove the foreign key for ros_pl.tag_details→tag_finder_id:pltagdetailstgfinderid
ALTER TABLE ros_pl.tag_details DROP CONSTRAINT pltagdetailstgfinderid;
-- remove the foreign key for ros_ps.observer_data→creator_id:psbserverdatacreatorid
ALTER TABLE ros_ps.observer_data DROP CONSTRAINT psbserverdatacreatorid;
-- remove the foreign key for ros_ps.observer_data→submitter_id:psbserverdatasbmtterid
ALTER TABLE ros_ps.observer_data DROP CONSTRAINT psbserverdatasbmtterid;
-- remove the foreign key for ros_ps.tag_details→tag_finder_id:pstagdetailstgfinderid
ALTER TABLE ros_ps.tag_details DROP CONSTRAINT pstagdetailstgfinderid;
UPDATE ros_common.contact_role SET contact_id = 142 WHERE contact_id = 145;
UPDATE ros_common.contact_role SET contact_id = 143 WHERE contact_id = 147;
UPDATE ros_common.contact_role SET contact_id = 144 WHERE contact_id = 148;
UPDATE ros_common.contact_role SET contact_id = 145 WHERE contact_id = 152;
UPDATE ros_common.contact_role SET contact_id = 146 WHERE contact_id = 182;
UPDATE ros_common.contact_role SET contact_id = 147 WHERE contact_id = 183;
UPDATE ros_common.contact_role SET contact_id = 148 WHERE contact_id = 184;
UPDATE ros_common.contact_role SET contact_id = 149 WHERE contact_id = 190;
UPDATE ros_common.contact_role SET contact_id = 150 WHERE contact_id = 192;
UPDATE ros_common.contact_role SET contact_id = 151 WHERE contact_id = 199;
UPDATE ros_common.contact_role SET contact_id = 152 WHERE contact_id = 200;
UPDATE ros_common.contact_role SET contact_id = 153 WHERE contact_id = 201;
UPDATE ros_common.contact_role SET contact_id = 154 WHERE contact_id = 202;
UPDATE ros_common.contact_role SET contact_id = 155 WHERE contact_id = 203;
UPDATE ros_common.contact_role SET contact_id = 156 WHERE contact_id = 204;
UPDATE ros_common.contact_role SET contact_id = 157 WHERE contact_id = 205;
UPDATE ros_common.contact_role SET contact_id = 158 WHERE contact_id = 206;
UPDATE ros_common.contact_role SET contact_id = 159 WHERE contact_id = 207;
UPDATE ros_common.observer SET contact_id = 157 WHERE contact_id = 205;
UPDATE ros_common.observer SET contact_id = 158 WHERE contact_id = 206;
UPDATE ros_common.observer SET contact_id = 159 WHERE contact_id = 207;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 145 WHERE fishing_master_id = 152;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 151 WHERE fishing_master_id = 199;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 152 WHERE fishing_master_id = 200;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 153 WHERE fishing_master_id = 201;
UPDATE ros_common.vessel_owner_and_personnel SET fishing_master_id = 154 WHERE fishing_master_id = 202;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 142 WHERE skipper_id = 145;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 143 WHERE skipper_id = 147;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 144 WHERE skipper_id = 148;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 145 WHERE skipper_id = 152;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 146 WHERE skipper_id = 182;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 147 WHERE skipper_id = 183;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 148 WHERE skipper_id = 184;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 149 WHERE skipper_id = 190;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 150 WHERE skipper_id = 192;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 152 WHERE skipper_id = 200;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 153 WHERE skipper_id = 201;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 154 WHERE skipper_id = 202;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 155 WHERE skipper_id = 203;
UPDATE ros_common.vessel_owner_and_personnel SET skipper_id = 156 WHERE skipper_id = 204;
UPDATE ros_common.contact SET id = 142 WHERE id = 145;
UPDATE ros_common.contact SET id = 143 WHERE id = 147;
UPDATE ros_common.contact SET id = 144 WHERE id = 148;
UPDATE ros_common.contact SET id = 145 WHERE id = 152;
UPDATE ros_common.contact SET id = 146 WHERE id = 182;
UPDATE ros_common.contact SET id = 147 WHERE id = 183;
UPDATE ros_common.contact SET id = 148 WHERE id = 184;
UPDATE ros_common.contact SET id = 149 WHERE id = 190;
UPDATE ros_common.contact SET id = 150 WHERE id = 192;
UPDATE ros_common.contact SET id = 151 WHERE id = 199;
UPDATE ros_common.contact SET id = 152 WHERE id = 200;
UPDATE ros_common.contact SET id = 153 WHERE id = 201;
UPDATE ros_common.contact SET id = 154 WHERE id = 202;
UPDATE ros_common.contact SET id = 155 WHERE id = 203;
UPDATE ros_common.contact SET id = 156 WHERE id = 204;
UPDATE ros_common.contact SET id = 157 WHERE id = 205;
UPDATE ros_common.contact SET id = 158 WHERE id = 206;
UPDATE ros_common.contact SET id = 159 WHERE id = 207;
ALTER TABLE ros_common.contact ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
-- add 16 foreign key(s) from ros_common.contact→id
-- add the foreign key fk_ros_common_contact_contact_role for ros_common.contact_role→contact_id:fk_ros_common_contact_contact_role
ALTER TABLE ros_common.contact_role ADD CONSTRAINT fk_ros_common_contact_contact_role FOREIGN KEY (contact_id) REFERENCES ros_common.contact(id);
-- add the foreign key fk_ros_common_contact_id_observer for ros_common.observer→contact_id:fk_ros_common_contact_id_observer
ALTER TABLE ros_common.observer ADD CONSTRAINT fk_ros_common_contact_id_observer FOREIGN KEY (contact_id) REFERENCES ros_common.contact(id);
-- add the foreign key vsslwnrndprsfshngmstrd for ros_common.vessel_owner_and_personnel→fishing_master_id:vsslwnrndprsfshngmstrd
ALTER TABLE ros_common.vessel_owner_and_personnel ADD CONSTRAINT vsslwnrndprsfshngmstrd FOREIGN KEY (fishing_master_id) REFERENCES ros_common.contact(id);
-- add the foreign key vsslwnrndprsnnelskpprd for ros_common.vessel_owner_and_personnel→skipper_id:vsslwnrndprsnnelskpprd
ALTER TABLE ros_common.vessel_owner_and_personnel ADD CONSTRAINT vsslwnrndprsnnelskpprd FOREIGN KEY (skipper_id) REFERENCES ros_common.contact(id);
-- add the foreign key gnbserverdatacreatorid for ros_gn.observer_data→creator_id:gnbserverdatacreatorid
ALTER TABLE ros_gn.observer_data ADD CONSTRAINT gnbserverdatacreatorid FOREIGN KEY (creator_id) REFERENCES ros_common.contact(id);
-- add the foreign key gnbserverdatasbmtterid for ros_gn.observer_data→submitter_id:gnbserverdatasbmtterid
ALTER TABLE ros_gn.observer_data ADD CONSTRAINT gnbserverdatasbmtterid FOREIGN KEY (submitter_id) REFERENCES ros_common.contact(id);
-- add the foreign key gntagdetailstgfinderid for ros_gn.tag_details→tag_finder_id:gntagdetailstgfinderid
ALTER TABLE ros_gn.tag_details ADD CONSTRAINT gntagdetailstgfinderid FOREIGN KEY (tag_finder_id) REFERENCES ros_common.contact(id);
-- add the foreign key llbserverdatacreatorid for ros_ll.observer_data→creator_id:llbserverdatacreatorid
ALTER TABLE ros_ll.observer_data ADD CONSTRAINT llbserverdatacreatorid FOREIGN KEY (creator_id) REFERENCES ros_common.contact(id);
-- add the foreign key llbserverdatasbmtterid for ros_ll.observer_data→submitter_id:llbserverdatasbmtterid
ALTER TABLE ros_ll.observer_data ADD CONSTRAINT llbserverdatasbmtterid FOREIGN KEY (submitter_id) REFERENCES ros_common.contact(id);
-- add the foreign key lltagdetailstgfinderid for ros_ll.tag_details→tag_finder_id:lltagdetailstgfinderid
ALTER TABLE ros_ll.tag_details ADD CONSTRAINT lltagdetailstgfinderid FOREIGN KEY (tag_finder_id) REFERENCES ros_common.contact(id);
-- add the foreign key plbserverdatacreatorid for ros_pl.observer_data→creator_id:plbserverdatacreatorid
ALTER TABLE ros_pl.observer_data ADD CONSTRAINT plbserverdatacreatorid FOREIGN KEY (creator_id) REFERENCES ros_common.contact(id);
-- add the foreign key plbserverdatasbmtterid for ros_pl.observer_data→submitter_id:plbserverdatasbmtterid
ALTER TABLE ros_pl.observer_data ADD CONSTRAINT plbserverdatasbmtterid FOREIGN KEY (submitter_id) REFERENCES ros_common.contact(id);
-- add the foreign key pltagdetailstgfinderid for ros_pl.tag_details→tag_finder_id:pltagdetailstgfinderid
ALTER TABLE ros_pl.tag_details ADD CONSTRAINT pltagdetailstgfinderid FOREIGN KEY (tag_finder_id) REFERENCES ros_common.contact(id);
-- add the foreign key psbserverdatacreatorid for ros_ps.observer_data→creator_id:psbserverdatacreatorid
ALTER TABLE ros_ps.observer_data ADD CONSTRAINT psbserverdatacreatorid FOREIGN KEY (creator_id) REFERENCES ros_common.contact(id);
-- add the foreign key psbserverdatasbmtterid for ros_ps.observer_data→submitter_id:psbserverdatasbmtterid
ALTER TABLE ros_ps.observer_data ADD CONSTRAINT psbserverdatasbmtterid FOREIGN KEY (submitter_id) REFERENCES ros_common.contact(id);
-- add the foreign key pstagdetailstgfinderid for ros_ps.tag_details→tag_finder_id:pstagdetailstgfinderid
ALTER TABLE ros_ps.tag_details ADD CONSTRAINT pstagdetailstgfinderid FOREIGN KEY (tag_finder_id) REFERENCES ros_common.contact(id);
select setval('ros_common.contact_id_seq', (select max(id) from ros_common.contact));INSERT INTO ros_common.vessel_identification (imo_identifier, iotc_vessel_identifier, ircs_identifier, vessel_name, registration_identifier,main_fishing_gear_code, flag_code) VALUES( NULL, 'IOTC001140', 'FGA4525', 'CHARLES 5', '899774', 'LL', 'FRA');
