ALTER TABLE ros_common.locations RENAME COLUMN "NAME" TO location_name;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 123 WHERE disembarkation_location_id = 124;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 123 WHERE embarkation_location_id = 124;
DELETE FROM ros_common.locations WHERE id = 124;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 18 WHERE disembarkation_location_id = 43;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 18 WHERE embarkation_location_id = 43;
DELETE FROM ros_common.locations WHERE id = 43;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 7;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 8;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 9;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 10;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 15;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 16;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 17;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 19;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 20;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 21;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 23;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 24;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 25;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 30;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 31;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 32;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 33;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 34;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 35;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 36;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 37;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 38;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 39;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 41;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 42;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 50;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 51;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 52;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 56;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 57;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 58;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 59;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 60;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 61;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 62;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 63;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 64;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 7;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 8;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 9;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 10;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 15;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 16;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 17;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 19;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 20;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 21;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 23;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 24;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 25;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 30;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 31;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 32;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 33;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 34;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 35;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 36;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 37;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 38;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 39;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 41;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 42;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 50;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 51;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 52;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 56;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 57;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 58;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 59;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 60;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 61;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 62;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 63;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 6 WHERE embarkation_location_id = 64;
DELETE FROM ros_common.locations WHERE id = 7;
DELETE FROM ros_common.locations WHERE id = 8;
DELETE FROM ros_common.locations WHERE id = 9;
DELETE FROM ros_common.locations WHERE id = 10;
DELETE FROM ros_common.locations WHERE id = 15;
DELETE FROM ros_common.locations WHERE id = 16;
DELETE FROM ros_common.locations WHERE id = 17;
DELETE FROM ros_common.locations WHERE id = 19;
DELETE FROM ros_common.locations WHERE id = 20;
DELETE FROM ros_common.locations WHERE id = 21;
DELETE FROM ros_common.locations WHERE id = 23;
DELETE FROM ros_common.locations WHERE id = 24;
DELETE FROM ros_common.locations WHERE id = 25;
DELETE FROM ros_common.locations WHERE id = 30;
DELETE FROM ros_common.locations WHERE id = 31;
DELETE FROM ros_common.locations WHERE id = 32;
DELETE FROM ros_common.locations WHERE id = 33;
DELETE FROM ros_common.locations WHERE id = 34;
DELETE FROM ros_common.locations WHERE id = 35;
DELETE FROM ros_common.locations WHERE id = 36;
DELETE FROM ros_common.locations WHERE id = 37;
DELETE FROM ros_common.locations WHERE id = 38;
DELETE FROM ros_common.locations WHERE id = 39;
DELETE FROM ros_common.locations WHERE id = 41;
DELETE FROM ros_common.locations WHERE id = 42;
DELETE FROM ros_common.locations WHERE id = 50;
DELETE FROM ros_common.locations WHERE id = 51;
DELETE FROM ros_common.locations WHERE id = 52;
DELETE FROM ros_common.locations WHERE id = 56;
DELETE FROM ros_common.locations WHERE id = 57;
DELETE FROM ros_common.locations WHERE id = 58;
DELETE FROM ros_common.locations WHERE id = 59;
DELETE FROM ros_common.locations WHERE id = 60;
DELETE FROM ros_common.locations WHERE id = 61;
DELETE FROM ros_common.locations WHERE id = 62;
DELETE FROM ros_common.locations WHERE id = 63;
DELETE FROM ros_common.locations WHERE id = 64;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 2;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 3;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 4;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 11;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 12;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 13;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 14;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 22;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 27;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 40;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 45;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 46;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 47;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 54;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 1 WHERE disembarkation_location_id = 55;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 2;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 3;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 4;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 11;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 12;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 13;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 14;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 22;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 27;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 40;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 45;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 46;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 47;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 54;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 1 WHERE embarkation_location_id = 55;
DELETE FROM ros_common.locations WHERE id = 2;
DELETE FROM ros_common.locations WHERE id = 3;
DELETE FROM ros_common.locations WHERE id = 4;
DELETE FROM ros_common.locations WHERE id = 11;
DELETE FROM ros_common.locations WHERE id = 12;
DELETE FROM ros_common.locations WHERE id = 13;
DELETE FROM ros_common.locations WHERE id = 14;
DELETE FROM ros_common.locations WHERE id = 22;
DELETE FROM ros_common.locations WHERE id = 27;
DELETE FROM ros_common.locations WHERE id = 40;
DELETE FROM ros_common.locations WHERE id = 45;
DELETE FROM ros_common.locations WHERE id = 46;
DELETE FROM ros_common.locations WHERE id = 47;
DELETE FROM ros_common.locations WHERE id = 54;
DELETE FROM ros_common.locations WHERE id = 55;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 111 WHERE disembarkation_location_id = 112;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 111 WHERE disembarkation_location_id = 113;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 111 WHERE disembarkation_location_id = 114;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 111 WHERE disembarkation_location_id = 115;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 111 WHERE disembarkation_location_id = 116;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 111 WHERE disembarkation_location_id = 117;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 111 WHERE disembarkation_location_id = 118;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 111 WHERE disembarkation_location_id = 121;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 111 WHERE disembarkation_location_id = 122;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 111 WHERE disembarkation_location_id = 125;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 111 WHERE disembarkation_location_id = 126;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 111 WHERE disembarkation_location_id = 127;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 111 WHERE disembarkation_location_id = 128;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 111 WHERE embarkation_location_id = 112;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 111 WHERE embarkation_location_id = 113;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 111 WHERE embarkation_location_id = 114;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 111 WHERE embarkation_location_id = 115;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 111 WHERE embarkation_location_id = 116;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 111 WHERE embarkation_location_id = 117;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 111 WHERE embarkation_location_id = 118;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 111 WHERE embarkation_location_id = 121;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 111 WHERE embarkation_location_id = 122;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 111 WHERE embarkation_location_id = 125;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 111 WHERE embarkation_location_id = 126;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 111 WHERE embarkation_location_id = 127;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 111 WHERE embarkation_location_id = 128;
DELETE FROM ros_common.locations WHERE id = 112;
DELETE FROM ros_common.locations WHERE id = 113;
DELETE FROM ros_common.locations WHERE id = 114;
DELETE FROM ros_common.locations WHERE id = 115;
DELETE FROM ros_common.locations WHERE id = 116;
DELETE FROM ros_common.locations WHERE id = 117;
DELETE FROM ros_common.locations WHERE id = 118;
DELETE FROM ros_common.locations WHERE id = 121;
DELETE FROM ros_common.locations WHERE id = 122;
DELETE FROM ros_common.locations WHERE id = 125;
DELETE FROM ros_common.locations WHERE id = 126;
DELETE FROM ros_common.locations WHERE id = 127;
DELETE FROM ros_common.locations WHERE id = 128;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 119 WHERE disembarkation_location_id = 120;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 119 WHERE embarkation_location_id = 120;
DELETE FROM ros_common.locations WHERE id = 120;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 29 WHERE disembarkation_location_id = 53;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 29 WHERE disembarkation_location_id = 89;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 29 WHERE embarkation_location_id = 53;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 29 WHERE embarkation_location_id = 89;
DELETE FROM ros_common.locations WHERE id = 53;
DELETE FROM ros_common.locations WHERE id = 89;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 66;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 67;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 68;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 69;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 70;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 71;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 72;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 73;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 74;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 75;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 76;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 77;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 78;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 79;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 80;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 81;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 82;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 83;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 84;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 85;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 86;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 87;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 88;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 90;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 91;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 92;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 93;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 94;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 95;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 96;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 97;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 98;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 99;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 100;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 101;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 103;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 104;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 105;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 106;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 107;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 108;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 109;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 65 WHERE disembarkation_location_id = 110;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 66;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 67;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 68;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 69;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 70;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 71;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 72;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 73;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 74;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 75;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 76;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 77;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 78;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 79;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 80;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 81;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 82;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 83;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 84;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 85;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 86;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 87;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 88;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 90;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 91;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 92;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 93;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 94;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 95;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 96;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 97;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 98;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 99;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 100;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 101;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 103;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 104;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 105;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 106;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 107;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 108;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 109;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 65 WHERE embarkation_location_id = 110;
DELETE FROM ros_common.locations WHERE id = 66;
DELETE FROM ros_common.locations WHERE id = 67;
DELETE FROM ros_common.locations WHERE id = 68;
DELETE FROM ros_common.locations WHERE id = 69;
DELETE FROM ros_common.locations WHERE id = 70;
DELETE FROM ros_common.locations WHERE id = 71;
DELETE FROM ros_common.locations WHERE id = 72;
DELETE FROM ros_common.locations WHERE id = 73;
DELETE FROM ros_common.locations WHERE id = 74;
DELETE FROM ros_common.locations WHERE id = 75;
DELETE FROM ros_common.locations WHERE id = 76;
DELETE FROM ros_common.locations WHERE id = 77;
DELETE FROM ros_common.locations WHERE id = 78;
DELETE FROM ros_common.locations WHERE id = 79;
DELETE FROM ros_common.locations WHERE id = 80;
DELETE FROM ros_common.locations WHERE id = 81;
DELETE FROM ros_common.locations WHERE id = 82;
DELETE FROM ros_common.locations WHERE id = 83;
DELETE FROM ros_common.locations WHERE id = 84;
DELETE FROM ros_common.locations WHERE id = 85;
DELETE FROM ros_common.locations WHERE id = 86;
DELETE FROM ros_common.locations WHERE id = 87;
DELETE FROM ros_common.locations WHERE id = 88;
DELETE FROM ros_common.locations WHERE id = 90;
DELETE FROM ros_common.locations WHERE id = 91;
DELETE FROM ros_common.locations WHERE id = 92;
DELETE FROM ros_common.locations WHERE id = 93;
DELETE FROM ros_common.locations WHERE id = 94;
DELETE FROM ros_common.locations WHERE id = 95;
DELETE FROM ros_common.locations WHERE id = 96;
DELETE FROM ros_common.locations WHERE id = 97;
DELETE FROM ros_common.locations WHERE id = 98;
DELETE FROM ros_common.locations WHERE id = 99;
DELETE FROM ros_common.locations WHERE id = 100;
DELETE FROM ros_common.locations WHERE id = 101;
DELETE FROM ros_common.locations WHERE id = 103;
DELETE FROM ros_common.locations WHERE id = 104;
DELETE FROM ros_common.locations WHERE id = 105;
DELETE FROM ros_common.locations WHERE id = 106;
DELETE FROM ros_common.locations WHERE id = 107;
DELETE FROM ros_common.locations WHERE id = 108;
DELETE FROM ros_common.locations WHERE id = 109;
DELETE FROM ros_common.locations WHERE id = 110;
ALTER TABLE ros_common.locations ALTER COLUMN id DROP IDENTITY;
-- remove 2 foreign key(s) from ros_common.locations→id
-- remove the foreign key for ros_common.observer_trip_details→disembarkation_location_id:bsrvrtrpddsmbrktnlctnd
ALTER TABLE ros_common.observer_trip_details DROP CONSTRAINT bsrvrtrpddsmbrktnlctnd;
-- remove the foreign key for ros_common.observer_trip_details→embarkation_location_id:bsrvrtrpdtlmbrktnlctnd
ALTER TABLE ros_common.observer_trip_details DROP CONSTRAINT bsrvrtrpdtlmbrktnlctnd;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 2 WHERE disembarkation_location_id = 5;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 3 WHERE disembarkation_location_id = 6;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 5 WHERE disembarkation_location_id = 26;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 6 WHERE disembarkation_location_id = 28;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 7 WHERE disembarkation_location_id = 29;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 8 WHERE disembarkation_location_id = 44;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 9 WHERE disembarkation_location_id = 48;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 11 WHERE disembarkation_location_id = 65;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 13 WHERE disembarkation_location_id = 111;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 14 WHERE disembarkation_location_id = 119;
UPDATE ros_common.observer_trip_details SET disembarkation_location_id = 15 WHERE disembarkation_location_id = 123;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 3 WHERE embarkation_location_id = 6;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 4 WHERE embarkation_location_id = 18;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 10 WHERE embarkation_location_id = 49;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 11 WHERE embarkation_location_id = 65;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 12 WHERE embarkation_location_id = 102;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 13 WHERE embarkation_location_id = 111;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 14 WHERE embarkation_location_id = 119;
UPDATE ros_common.observer_trip_details SET embarkation_location_id = 15 WHERE embarkation_location_id = 123;
UPDATE ros_common.locations SET id = 2 WHERE id = 5;
UPDATE ros_common.locations SET id = 3 WHERE id = 6;
UPDATE ros_common.locations SET id = 4 WHERE id = 18;
UPDATE ros_common.locations SET id = 5 WHERE id = 26;
UPDATE ros_common.locations SET id = 6 WHERE id = 28;
UPDATE ros_common.locations SET id = 7 WHERE id = 29;
UPDATE ros_common.locations SET id = 8 WHERE id = 44;
UPDATE ros_common.locations SET id = 9 WHERE id = 48;
UPDATE ros_common.locations SET id = 10 WHERE id = 49;
UPDATE ros_common.locations SET id = 11 WHERE id = 65;
UPDATE ros_common.locations SET id = 12 WHERE id = 102;
UPDATE ros_common.locations SET id = 13 WHERE id = 111;
UPDATE ros_common.locations SET id = 14 WHERE id = 119;
UPDATE ros_common.locations SET id = 15 WHERE id = 123;
ALTER TABLE ros_common.locations ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
-- add 2 foreign key(s) from ros_common.locations→id
-- add the foreign key bsrvrtrpddsmbrktnlctnd for ros_common.observer_trip_details→disembarkation_location_id:bsrvrtrpddsmbrktnlctnd
ALTER TABLE ros_common.observer_trip_details ADD CONSTRAINT bsrvrtrpddsmbrktnlctnd FOREIGN KEY (disembarkation_location_id) REFERENCES ros_common.locations(id);
-- add the foreign key bsrvrtrpdtlmbrktnlctnd for ros_common.observer_trip_details→embarkation_location_id:bsrvrtrpdtlmbrktnlctnd
ALTER TABLE ros_common.observer_trip_details ADD CONSTRAINT bsrvrtrpdtlmbrktnlctnd FOREIGN KEY (embarkation_location_id) REFERENCES ros_common.locations(id);
UPDATE ros_common.locations SET country_code = 'SYC' WHERE id = 11;
UPDATE ros_common.locations SET country_code = 'LKA' WHERE id = 12;
UPDATE ros_common.locations SET country_code = 'LKA' WHERE id = 13;
UPDATE ros_common.locations SET latitude = NULL, longitude = NULL WHERE latitude = 0 AND longitude = 0;
UPDATE ros_common.locations SET latitude = -33.917, longitude = 18.417 WHERE id = 1;
UPDATE ros_common.locations SET latitude = -8.767, longitude = 115.217 WHERE id = 3;
UPDATE ros_common.locations SET latitude = -29.85, longitude = 31.017 WHERE id = 6;
UPDATE ros_common.locations SET latitude = 6.035, longitude = 80.229 WHERE id = 12;
UPDATE ros_common.locations SET latitude = 6.917, longitude = 79.85 WHERE id = 13;
UPDATE ros_common.locations SET latitude = 7.002, longitude = 79.868 WHERE id = 14;

