ALTER TABLE ros_ll.observer_data ALTER COLUMN id DROP IDENTITY;
-- remove 2 foreign key(s) from ros_ll.observer_data→id
-- remove the foreign key for ros_ll.observer_data_properties→observer_data_id:llbsrvrdtprprtbsrvrdtd
ALTER TABLE ros_ll.observer_data_properties DROP CONSTRAINT llbsrvrdtprprtbsrvrdtd;
-- remove the foreign key for ros_ll.fishing_events→observer_data_id:llfshngvntsllbsrvrdtid
ALTER TABLE ros_ll.fishing_events DROP CONSTRAINT llfshngvntsllbsrvrdtid;
UPDATE ros_ll.fishing_events SET observer_data_id = 692 WHERE observer_data_id = 712;
UPDATE ros_ll.fishing_events SET observer_data_id = 693 WHERE observer_data_id = 713;
UPDATE ros_ll.fishing_events SET observer_data_id = 694 WHERE observer_data_id = 714;
UPDATE ros_ll.fishing_events SET observer_data_id = 695 WHERE observer_data_id = 715;
UPDATE ros_ll.fishing_events SET observer_data_id = 696 WHERE observer_data_id = 716;
UPDATE ros_ll.fishing_events SET observer_data_id = 697 WHERE observer_data_id = 717;
UPDATE ros_ll.fishing_events SET observer_data_id = 698 WHERE observer_data_id = 718;
UPDATE ros_ll.fishing_events SET observer_data_id = 699 WHERE observer_data_id = 719;
UPDATE ros_ll.fishing_events SET observer_data_id = 700 WHERE observer_data_id = 720;
UPDATE ros_ll.fishing_events SET observer_data_id = 701 WHERE observer_data_id = 721;
UPDATE ros_ll.fishing_events SET observer_data_id = 703 WHERE observer_data_id = 723;
UPDATE ros_ll.fishing_events SET observer_data_id = 704 WHERE observer_data_id = 724;
UPDATE ros_ll.fishing_events SET observer_data_id = 705 WHERE observer_data_id = 725;
UPDATE ros_ll.fishing_events SET observer_data_id = 706 WHERE observer_data_id = 726;
UPDATE ros_ll.fishing_events SET observer_data_id = 707 WHERE observer_data_id = 727;
UPDATE ros_ll.fishing_events SET observer_data_id = 708 WHERE observer_data_id = 728;
UPDATE ros_ll.fishing_events SET observer_data_id = 709 WHERE observer_data_id = 729;
UPDATE ros_ll.fishing_events SET observer_data_id = 713 WHERE observer_data_id = 733;
UPDATE ros_ll.fishing_events SET observer_data_id = 714 WHERE observer_data_id = 734;
UPDATE ros_ll.fishing_events SET observer_data_id = 715 WHERE observer_data_id = 735;
UPDATE ros_ll.fishing_events SET observer_data_id = 716 WHERE observer_data_id = 736;
UPDATE ros_ll.fishing_events SET observer_data_id = 717 WHERE observer_data_id = 737;
UPDATE ros_ll.fishing_events SET observer_data_id = 718 WHERE observer_data_id = 738;
UPDATE ros_ll.fishing_events SET observer_data_id = 719 WHERE observer_data_id = 739;
UPDATE ros_ll.fishing_events SET observer_data_id = 720 WHERE observer_data_id = 740;
UPDATE ros_ll.fishing_events SET observer_data_id = 721 WHERE observer_data_id = 741;
UPDATE ros_ll.fishing_events SET observer_data_id = 722 WHERE observer_data_id = 742;
UPDATE ros_ll.fishing_events SET observer_data_id = 723 WHERE observer_data_id = 743;
UPDATE ros_ll.fishing_events SET observer_data_id = 724 WHERE observer_data_id = 744;
UPDATE ros_ll.fishing_events SET observer_data_id = 725 WHERE observer_data_id = 745;
UPDATE ros_ll.fishing_events SET observer_data_id = 726 WHERE observer_data_id = 746;
UPDATE ros_ll.fishing_events SET observer_data_id = 727 WHERE observer_data_id = 747;
UPDATE ros_ll.fishing_events SET observer_data_id = 728 WHERE observer_data_id = 748;
UPDATE ros_ll.fishing_events SET observer_data_id = 729 WHERE observer_data_id = 749;
UPDATE ros_ll.fishing_events SET observer_data_id = 730 WHERE observer_data_id = 750;
UPDATE ros_ll.fishing_events SET observer_data_id = 731 WHERE observer_data_id = 751;
UPDATE ros_ll.fishing_events SET observer_data_id = 732 WHERE observer_data_id = 752;
UPDATE ros_ll.fishing_events SET observer_data_id = 733 WHERE observer_data_id = 753;
UPDATE ros_ll.fishing_events SET observer_data_id = 734 WHERE observer_data_id = 754;
UPDATE ros_ll.fishing_events SET observer_data_id = 735 WHERE observer_data_id = 755;
UPDATE ros_ll.fishing_events SET observer_data_id = 736 WHERE observer_data_id = 756;
UPDATE ros_ll.fishing_events SET observer_data_id = 737 WHERE observer_data_id = 757;
UPDATE ros_ll.fishing_events SET observer_data_id = 738 WHERE observer_data_id = 758;
UPDATE ros_ll.fishing_events SET observer_data_id = 739 WHERE observer_data_id = 759;
UPDATE ros_ll.fishing_events SET observer_data_id = 740 WHERE observer_data_id = 760;
UPDATE ros_ll.fishing_events SET observer_data_id = 741 WHERE observer_data_id = 761;
UPDATE ros_ll.fishing_events SET observer_data_id = 742 WHERE observer_data_id = 762;
UPDATE ros_ll.fishing_events SET observer_data_id = 743 WHERE observer_data_id = 774;
UPDATE ros_ll.fishing_events SET observer_data_id = 744 WHERE observer_data_id = 775;
UPDATE ros_ll.fishing_events SET observer_data_id = 745 WHERE observer_data_id = 776;
UPDATE ros_ll.fishing_events SET observer_data_id = 746 WHERE observer_data_id = 778;
UPDATE ros_ll.fishing_events SET observer_data_id = 747 WHERE observer_data_id = 779;
UPDATE ros_ll.fishing_events SET observer_data_id = 748 WHERE observer_data_id = 781;
UPDATE ros_ll.fishing_events SET observer_data_id = 749 WHERE observer_data_id = 782;
UPDATE ros_ll.fishing_events SET observer_data_id = 750 WHERE observer_data_id = 783;
UPDATE ros_ll.fishing_events SET observer_data_id = 751 WHERE observer_data_id = 784;
UPDATE ros_ll.observer_data SET id = 692 WHERE id = 712;
UPDATE ros_ll.observer_data SET id = 693 WHERE id = 713;
UPDATE ros_ll.observer_data SET id = 694 WHERE id = 714;
UPDATE ros_ll.observer_data SET id = 695 WHERE id = 715;
UPDATE ros_ll.observer_data SET id = 696 WHERE id = 716;
UPDATE ros_ll.observer_data SET id = 697 WHERE id = 717;
UPDATE ros_ll.observer_data SET id = 698 WHERE id = 718;
UPDATE ros_ll.observer_data SET id = 699 WHERE id = 719;
UPDATE ros_ll.observer_data SET id = 700 WHERE id = 720;
UPDATE ros_ll.observer_data SET id = 701 WHERE id = 721;
UPDATE ros_ll.observer_data SET id = 702 WHERE id = 722;
UPDATE ros_ll.observer_data SET id = 703 WHERE id = 723;
UPDATE ros_ll.observer_data SET id = 704 WHERE id = 724;
UPDATE ros_ll.observer_data SET id = 705 WHERE id = 725;
UPDATE ros_ll.observer_data SET id = 706 WHERE id = 726;
UPDATE ros_ll.observer_data SET id = 707 WHERE id = 727;
UPDATE ros_ll.observer_data SET id = 708 WHERE id = 728;
UPDATE ros_ll.observer_data SET id = 709 WHERE id = 729;
UPDATE ros_ll.observer_data SET id = 710 WHERE id = 730;
UPDATE ros_ll.observer_data SET id = 711 WHERE id = 731;
UPDATE ros_ll.observer_data SET id = 712 WHERE id = 732;
UPDATE ros_ll.observer_data SET id = 713 WHERE id = 733;
UPDATE ros_ll.observer_data SET id = 714 WHERE id = 734;
UPDATE ros_ll.observer_data SET id = 715 WHERE id = 735;
UPDATE ros_ll.observer_data SET id = 716 WHERE id = 736;
UPDATE ros_ll.observer_data SET id = 717 WHERE id = 737;
UPDATE ros_ll.observer_data SET id = 718 WHERE id = 738;
UPDATE ros_ll.observer_data SET id = 719 WHERE id = 739;
UPDATE ros_ll.observer_data SET id = 720 WHERE id = 740;
UPDATE ros_ll.observer_data SET id = 721 WHERE id = 741;
UPDATE ros_ll.observer_data SET id = 722 WHERE id = 742;
UPDATE ros_ll.observer_data SET id = 723 WHERE id = 743;
UPDATE ros_ll.observer_data SET id = 724 WHERE id = 744;
UPDATE ros_ll.observer_data SET id = 725 WHERE id = 745;
UPDATE ros_ll.observer_data SET id = 726 WHERE id = 746;
UPDATE ros_ll.observer_data SET id = 727 WHERE id = 747;
UPDATE ros_ll.observer_data SET id = 728 WHERE id = 748;
UPDATE ros_ll.observer_data SET id = 729 WHERE id = 749;
UPDATE ros_ll.observer_data SET id = 730 WHERE id = 750;
UPDATE ros_ll.observer_data SET id = 731 WHERE id = 751;
UPDATE ros_ll.observer_data SET id = 732 WHERE id = 752;
UPDATE ros_ll.observer_data SET id = 733 WHERE id = 753;
UPDATE ros_ll.observer_data SET id = 734 WHERE id = 754;
UPDATE ros_ll.observer_data SET id = 735 WHERE id = 755;
UPDATE ros_ll.observer_data SET id = 736 WHERE id = 756;
UPDATE ros_ll.observer_data SET id = 737 WHERE id = 757;
UPDATE ros_ll.observer_data SET id = 738 WHERE id = 758;
UPDATE ros_ll.observer_data SET id = 739 WHERE id = 759;
UPDATE ros_ll.observer_data SET id = 740 WHERE id = 760;
UPDATE ros_ll.observer_data SET id = 741 WHERE id = 761;
UPDATE ros_ll.observer_data SET id = 742 WHERE id = 762;
UPDATE ros_ll.observer_data SET id = 743 WHERE id = 774;
UPDATE ros_ll.observer_data SET id = 744 WHERE id = 775;
UPDATE ros_ll.observer_data SET id = 745 WHERE id = 776;
UPDATE ros_ll.observer_data SET id = 746 WHERE id = 778;
UPDATE ros_ll.observer_data SET id = 747 WHERE id = 779;
UPDATE ros_ll.observer_data SET id = 748 WHERE id = 781;
UPDATE ros_ll.observer_data SET id = 749 WHERE id = 782;
UPDATE ros_ll.observer_data SET id = 750 WHERE id = 783;
UPDATE ros_ll.observer_data SET id = 751 WHERE id = 784;
ALTER TABLE ros_ll.observer_data ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
-- add 2 foreign key(s) from ros_ll.observer_data→id
-- add the foreign key llbsrvrdtprprtbsrvrdtd for ros_ll.observer_data_properties→observer_data_id:llbsrvrdtprprtbsrvrdtd
ALTER TABLE ros_ll.observer_data_properties ADD CONSTRAINT llbsrvrdtprprtbsrvrdtd FOREIGN KEY (observer_data_id) REFERENCES ros_ll.observer_data(id);
-- add the foreign key llfshngvntsllbsrvrdtid for ros_ll.fishing_events→observer_data_id:llfshngvntsllbsrvrdtid
ALTER TABLE ros_ll.fishing_events ADD CONSTRAINT llfshngvntsllbsrvrdtid FOREIGN KEY (observer_data_id) REFERENCES ros_ll.observer_data(id);
