
ALTER TABLE ros_gn.gillnet_configuration_stretched_mesh_sizes DROP CONSTRAINT gngllntcnstrtchdmshszd;
ALTER TABLE ros_ps.general_gear_attributes DROP CONSTRAINT psgnrlbntstrtchdmshszd;
ALTER TABLE ros_ps.general_gear_attributes DROP CONSTRAINT psgnrmdntstrtchdmshszd;
INSERT INTO ros_common.sizes(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000000, 'MM', 110.0);
UPDATE ros_ps.general_gear_attributes SET bunt_stretched_mesh_size_id = 1000000 WHERE bunt_stretched_mesh_size_id IN (SELECT id FROM ros_common.sizes WHERE unit = 'MM' AND value = 110.0);
UPDATE ros_ps.general_gear_attributes SET mid_net_stretched_mesh_size_id = 1000000 WHERE mid_net_stretched_mesh_size_id IN (SELECT id FROM ros_common.sizes WHERE unit = 'MM' AND value = 110.0);
INSERT INTO ros_common.sizes(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000001, 'MM', 75.0);
UPDATE ros_ps.general_gear_attributes SET bunt_stretched_mesh_size_id = 1000001 WHERE bunt_stretched_mesh_size_id IN (SELECT id FROM ros_common.sizes WHERE unit = 'MM' AND value = 75.0);
UPDATE ros_ps.general_gear_attributes SET mid_net_stretched_mesh_size_id = 1000001 WHERE mid_net_stretched_mesh_size_id IN (SELECT id FROM ros_common.sizes WHERE unit = 'MM' AND value = 75.0);
INSERT INTO ros_common.sizes(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000002, 'MM', 200.0);
UPDATE ros_ps.general_gear_attributes SET bunt_stretched_mesh_size_id = 1000002 WHERE bunt_stretched_mesh_size_id IN (SELECT id FROM ros_common.sizes WHERE unit = 'MM' AND value = 200.0);
UPDATE ros_ps.general_gear_attributes SET mid_net_stretched_mesh_size_id = 1000002 WHERE mid_net_stretched_mesh_size_id IN (SELECT id FROM ros_common.sizes WHERE unit = 'MM' AND value = 200.0);
INSERT INTO ros_common.sizes(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000003, 'MM', 254.0);
UPDATE ros_ps.general_gear_attributes SET bunt_stretched_mesh_size_id = 1000003 WHERE bunt_stretched_mesh_size_id IN (SELECT id FROM ros_common.sizes WHERE unit = 'MM' AND value = 254.0);
UPDATE ros_ps.general_gear_attributes SET mid_net_stretched_mesh_size_id = 1000003 WHERE mid_net_stretched_mesh_size_id IN (SELECT id FROM ros_common.sizes WHERE unit = 'MM' AND value = 254.0);
INSERT INTO ros_common.sizes(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000004, 'MM', 203.2);
UPDATE ros_ps.general_gear_attributes SET bunt_stretched_mesh_size_id = 1000004 WHERE bunt_stretched_mesh_size_id IN (SELECT id FROM ros_common.sizes WHERE unit = 'MM' AND value = 203.2);
UPDATE ros_ps.general_gear_attributes SET mid_net_stretched_mesh_size_id = 1000004 WHERE mid_net_stretched_mesh_size_id IN (SELECT id FROM ros_common.sizes WHERE unit = 'MM' AND value = 203.2);
DELETE FROM ros_common.sizes WHERE id < 1000000;
INSERT INTO ros_common.sizes(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1, 'MM', 110.0);
INSERT INTO ros_common.sizes(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (2, 'MM', 75.0);
INSERT INTO ros_common.sizes(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (3, 'MM', 200.0);
INSERT INTO ros_common.sizes(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (4, 'MM', 254.0);
INSERT INTO ros_common.sizes(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (5, 'MM', 203.2);
UPDATE ros_ps.general_gear_attributes SET bunt_stretched_mesh_size_id = bunt_stretched_mesh_size_id - 1000000 + 1;
UPDATE ros_ps.general_gear_attributes SET mid_net_stretched_mesh_size_id = mid_net_stretched_mesh_size_id - 1000000 + 1;
DELETE FROM ros_common.sizes WHERE id >= 1000000;
ALTER TABLE ros_gn.gillnet_configuration_stretched_mesh_sizes ADD CONSTRAINT gngllntcnstrtchdmshszd FOREIGN KEY (stretched_mesh_size_id) references ros_common.sizes (id);
ALTER TABLE ros_ps.general_gear_attributes ADD CONSTRAINT psgnrlbntstrtchdmshszd FOREIGN KEY (bunt_stretched_mesh_size_id) references ros_common.sizes (id);
ALTER TABLE ros_ps.general_gear_attributes ADD CONSTRAINT psgnrmdntstrtchdmshszd FOREIGN KEY (mid_net_stretched_mesh_size_id) references ros_common.sizes (id);
ALTER TABLE ros_common.sizes ADD CONSTRAINT uk_sizes UNIQUE (unit,value);
