
ALTER TABLE ros_ll.branchline_sections DROP CONSTRAINT brnchlnesectionsdmtrid;
ALTER TABLE ros_ll.general_gear_attributes DROP CONSTRAINT llgnrlgrttrbtmnlndmtrd;
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000000, 'MM', 5.0);
UPDATE ros_ll.general_gear_attributes SET mainline_diameter_id = 1000000 WHERE mainline_diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 5.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000001, 'MM', 10.0);
UPDATE ros_ll.general_gear_attributes SET mainline_diameter_id = 1000001 WHERE mainline_diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 10.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000002, 'MM', 4.0);
UPDATE ros_ll.general_gear_attributes SET mainline_diameter_id = 1000002 WHERE mainline_diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 4.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000003, 'MM', 8.0);
UPDATE ros_ll.general_gear_attributes SET mainline_diameter_id = 1000003 WHERE mainline_diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 8.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000004, 'MM', 18.0);
UPDATE ros_ll.general_gear_attributes SET mainline_diameter_id = 1000004 WHERE mainline_diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 18.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000005, 'MM', 12.0);
UPDATE ros_ll.general_gear_attributes SET mainline_diameter_id = 1000005 WHERE mainline_diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 12.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000006, 'MM', 6.0);
UPDATE ros_ll.general_gear_attributes SET mainline_diameter_id = 1000006 WHERE mainline_diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 6.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000007, 'MM', 40.0);
UPDATE ros_ll.general_gear_attributes SET mainline_diameter_id = 1000007 WHERE mainline_diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 40.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000008, 'MM', 3.0);
UPDATE ros_ll.general_gear_attributes SET mainline_diameter_id = 1000008 WHERE mainline_diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 3.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000009, 'MM', 9.0);
UPDATE ros_ll.general_gear_attributes SET mainline_diameter_id = 1000009 WHERE mainline_diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 9.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000010, 'MM', 3.5);
UPDATE ros_ll.general_gear_attributes SET mainline_diameter_id = 1000010 WHERE mainline_diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 3.5);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000011, 'MM', 2.6);
UPDATE ros_ll.branchline_sections SET diameter_id = 1000011 WHERE diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 2.6);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000012, 'MM', 1.8);
UPDATE ros_ll.branchline_sections SET diameter_id = 1000012 WHERE diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 1.8);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000013, 'MM', 3.1);
UPDATE ros_ll.branchline_sections SET diameter_id = 1000013 WHERE diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 3.1);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000014, 'MM', 1.6);
UPDATE ros_ll.branchline_sections SET diameter_id = 1000014 WHERE diameter_id IN (SELECT id FROM ros_common.diameters WHERE unit = 'MM' AND value = 1.6);
DELETE FROM ros_common.diameters WHERE id < 1000000;
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1, 'MM', 5.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (2, 'MM', 10.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (3, 'MM', 4.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (4, 'MM', 8.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (5, 'MM', 18.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (6, 'MM', 12.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (7, 'MM', 6.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (8, 'MM', 40.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (9, 'MM', 3.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (10, 'MM', 9.0);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (11, 'MM', 3.5);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (12, 'MM', 2.6);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (13, 'MM', 1.8);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (14, 'MM', 3.1);
INSERT INTO ros_common.diameters(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (15, 'MM', 1.6);
UPDATE ros_ll.branchline_sections SET diameter_id = diameter_id - 1000000 + 1;
UPDATE ros_ll.general_gear_attributes SET mainline_diameter_id = mainline_diameter_id - 1000000 + 1;
DELETE FROM ros_common.diameters WHERE id >= 1000000;
ALTER TABLE ros_ll.branchline_sections ADD CONSTRAINT brnchlnesectionsdmtrid FOREIGN KEY (diameter_id) references ros_common.diameters (id);
ALTER TABLE ros_ll.general_gear_attributes ADD CONSTRAINT llgnrlgrttrbtmnlndmtrd FOREIGN KEY (mainline_diameter_id) references ros_common.diameters (id);
ALTER TABLE ros_common.diameters ADD CONSTRAINT uk_diameters UNIQUE (unit, value);
SELECT setval('ros_common.diameters_ID_seq', (SELECT COALESCE(MAX(id), 1) FROM ros_common.diameters));