
ALTER TABLE ros_pl.bait_fishing_operations DROP CONSTRAINT btfshngprtionsvntdpthd;
ALTER TABLE ros_gn.gillnet_configuration DROP CONSTRAINT gllntcnfgrationntdpthd;
ALTER TABLE ros_ps.general_gear_attributes DROP CONSTRAINT psgnrlgrttrmxmmntdpthd;
INSERT INTO ros_common.depths(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000000, 'M', 300.0);
UPDATE ros_ps.general_gear_attributes SET maximum_net_depth_id = 1000000 WHERE maximum_net_depth_id IN (SELECT id FROM ros_common.depths WHERE unit = 'M' AND value = 300.0);
INSERT INTO ros_common.depths(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000001, 'M', 200.0);
UPDATE ros_ps.general_gear_attributes SET maximum_net_depth_id = 1000001 WHERE maximum_net_depth_id IN (SELECT id FROM ros_common.depths WHERE unit = 'M' AND value = 200.0);
INSERT INTO ros_common.depths(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000002, 'M', 230.0);
UPDATE ros_ps.general_gear_attributes SET maximum_net_depth_id = 1000002 WHERE maximum_net_depth_id IN (SELECT id FROM ros_common.depths WHERE unit = 'M' AND value = 230.0);
INSERT INTO ros_common.depths(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000003, 'M', 315.0);
UPDATE ros_ps.general_gear_attributes SET maximum_net_depth_id = 1000003 WHERE maximum_net_depth_id IN (SELECT id FROM ros_common.depths WHERE unit = 'M' AND value = 315.0);
INSERT INTO ros_common.depths(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000004, 'M', 310.0);
UPDATE ros_ps.general_gear_attributes SET maximum_net_depth_id = 1000004 WHERE maximum_net_depth_id IN (SELECT id FROM ros_common.depths WHERE unit = 'M' AND value = 310.0);
DELETE FROM ros_common.depths WHERE id < 1000000;
INSERT INTO ros_common.depths(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1, 'M', 300.0);
INSERT INTO ros_common.depths(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (2, 'M', 200.0);
INSERT INTO ros_common.depths(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (3, 'M', 230.0);
INSERT INTO ros_common.depths(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (4, 'M', 315.0);
INSERT INTO ros_common.depths(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (5, 'M', 310.0);
UPDATE ros_ps.general_gear_attributes SET maximum_net_depth_id = maximum_net_depth_id - 1000000 + 1;
DELETE FROM ros_common.depths WHERE id >= 1000000;
ALTER TABLE ros_pl.bait_fishing_operations ADD CONSTRAINT btfshngprtionsvntdpthd FOREIGN KEY (event_depth_id) references ros_common.depths (id);
ALTER TABLE ros_gn.gillnet_configuration ADD CONSTRAINT gllntcnfgrationntdpthd FOREIGN KEY (net_depth_id) references ros_common.depths (id);
ALTER TABLE ros_ps.general_gear_attributes ADD CONSTRAINT psgnrlgrttrmxmmntdpthd FOREIGN KEY (maximum_net_depth_id) references ros_common.depths (id);
ALTER TABLE ros_common.depths ADD CONSTRAINT uk_depths UNIQUE (unit, value);
SELECT setval('ros_common.depths_ID_seq', (SELECT COALESCE(MAX(id), 1) FROM ros_common.depths));