
ALTER TABLE ros_common.vessel_attributes DROP CONSTRAINT vsslttrbtfshstrgcpctyd;
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000000, 'M3', 0.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000000 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 0.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000001, 'MT', 360.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000001 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 360.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000002, 'MT', 300.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000002 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 300.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000003, 'MT', 293.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000003 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 293.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000004, 'MT', 302.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000004 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 302.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000005, 'MT', 260.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000005 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 260.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000006, 'MT', 225.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000006 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 225.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000007, 'MT', 287.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000007 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 287.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000008, 'MT', 250.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000008 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 250.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000009, 'MT', 210.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000009 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 210.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000010, 'MT', 490.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000010 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 490.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000011, 'MT', 220.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000011 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 220.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000012, 'MT', 310.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000012 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 310.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000013, 'MT', 325.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000013 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 325.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000014, 'MT', 305.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000014 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 305.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000015, 'MT', 290.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000015 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 290.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000016, 'MT', 245.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000016 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 245.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000017, 'MT', 350.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000017 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 350.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000018, 'MT', 229.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000018 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 229.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000019, 'MT', 295.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000019 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 295.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000020, 'MT', 1029.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000020 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 1029.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000021, 'MT', 280.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000021 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 280.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000022, 'MT', 459.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000022 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 459.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000023, 'MT', 374.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000023 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 374.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000024, 'MT', 735.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000024 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 735.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000025, 'MT', 270.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000025 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 270.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000026, 'MT', 320.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000026 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 320.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000027, 'MT', 40.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000027 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 40.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000028, 'MT', 263.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000028 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 263.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000029, 'MT', 330.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000029 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 330.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000030, 'MT', 340.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000030 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 340.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000031, 'MT', 355.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000031 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 355.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000032, 'MT', 370.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000032 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 370.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000033, 'MT', 493.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000033 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'MT' AND value = 493.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000034, 'M3', 1750.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000034 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1750.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000035, 'M3', 2680.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000035 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2680.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000036, 'M3', 2000.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000036 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2000.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000037, 'M3', 1850.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000037 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1850.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000038, 'M3', 2900.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000038 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2900.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000039, 'M3', 3095.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000039 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 3095.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000040, 'M3', 1952.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000040 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1952.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000041, 'M3', 1900.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000041 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1900.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000042, 'M3', 2240.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000042 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2240.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000043, 'M3', 2250.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000043 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2250.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000044, 'M3', 2994.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000044 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2994.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000045, 'M3', 2828.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000045 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2828.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000046, 'M3', 1790.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000046 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1790.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000047, 'M3', 1742.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000047 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1742.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000048, 'M3', 1527.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000048 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1527.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000049, 'M3', 1200.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000049 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1200.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000050, 'M3', 1050.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000050 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1050.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000051, 'M3', 1206.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000051 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1206.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000052, 'M3', 1380.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000052 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1380.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000053, 'M3', 1800.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000053 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1800.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000054, 'M3', 1650.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000054 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1650.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000055, 'M3', 1470.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000055 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1470.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000056, 'M3', 2119.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000056 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2119.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000057, 'M3', 1519.05);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000057 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1519.05);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000058, 'M3', 17.7);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000058 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 17.7);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000059, 'M3', 2272.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000059 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2272.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000060, 'M3', 2966.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000060 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2966.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000061, 'M3', 1520.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000061 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1520.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000062, 'M3', 2355.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000062 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2355.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000063, 'M3', 2593.5);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000063 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2593.5);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000064, 'M3', 3250.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000064 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 3250.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000065, 'M3', 1450.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000065 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1450.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000066, 'M3', 2009.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000066 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2009.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000067, 'M3', 1130.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000067 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1130.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000068, 'M3', 1630.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000068 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1630.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000069, 'M3', 2238.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000069 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2238.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000070, 'M3', 1124.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000070 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1124.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000071, 'M3', 2218.8);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000071 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2218.8);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000072, 'M3', 1300.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000072 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 1300.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000073, 'M3', 2124.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000073 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 2124.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000074, 'M3', 17.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000074 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 17.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1000075, 'M3', 85.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = 1000075 WHERE fish_storage_capacity_id IN (SELECT id FROM ros_common.capacities WHERE unit = 'M3' AND value = 85.0);
DELETE FROM ros_common.capacities WHERE id < 1000000;
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (1, 'M3', 0.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (2, 'MT', 360.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (3, 'MT', 300.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (4, 'MT', 293.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (5, 'MT', 302.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (6, 'MT', 260.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (7, 'MT', 225.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (8, 'MT', 287.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (9, 'MT', 250.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (10, 'MT', 210.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (11, 'MT', 490.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (12, 'MT', 220.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (13, 'MT', 310.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (14, 'MT', 325.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (15, 'MT', 305.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (16, 'MT', 290.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (17, 'MT', 245.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (18, 'MT', 350.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (19, 'MT', 229.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (20, 'MT', 295.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (21, 'MT', 1029.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (22, 'MT', 280.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (23, 'MT', 459.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (24, 'MT', 374.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (25, 'MT', 735.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (26, 'MT', 270.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (27, 'MT', 320.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (28, 'MT', 40.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (29, 'MT', 263.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (30, 'MT', 330.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (31, 'MT', 340.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (32, 'MT', 355.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (33, 'MT', 370.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (34, 'MT', 493.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (35, 'M3', 1750.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (36, 'M3', 2680.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (37, 'M3', 2000.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (38, 'M3', 1850.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (39, 'M3', 2900.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (40, 'M3', 3095.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (41, 'M3', 1952.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (42, 'M3', 1900.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (43, 'M3', 2240.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (44, 'M3', 2250.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (45, 'M3', 2994.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (46, 'M3', 2828.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (47, 'M3', 1790.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (48, 'M3', 1742.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (49, 'M3', 1527.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (50, 'M3', 1200.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (51, 'M3', 1050.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (52, 'M3', 1206.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (53, 'M3', 1380.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (54, 'M3', 1800.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (55, 'M3', 1650.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (56, 'M3', 1470.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (57, 'M3', 2119.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (58, 'M3', 1519.05);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (59, 'M3', 17.7);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (60, 'M3', 2272.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (61, 'M3', 2966.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (62, 'M3', 1520.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (63, 'M3', 2355.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (64, 'M3', 2593.5);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (65, 'M3', 3250.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (66, 'M3', 1450.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (67, 'M3', 2009.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (68, 'M3', 1130.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (69, 'M3', 1630.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (70, 'M3', 2238.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (71, 'M3', 1124.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (72, 'M3', 2218.8);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (73, 'M3', 1300.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (74, 'M3', 2124.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (75, 'M3', 17.0);
INSERT INTO ros_common.capacities(id, unit, value) OVERRIDING SYSTEM VALUE VALUES (76, 'M3', 85.0);
UPDATE ros_common.vessel_attributes SET fish_storage_capacity_id = fish_storage_capacity_id - 1000000 + 1;
DELETE FROM ros_common.capacities WHERE id >= 1000000;
ALTER TABLE ros_common.vessel_attributes ADD CONSTRAINT vsslttrbtfshstrgcpctyd FOREIGN KEY (fish_storage_capacity_id) references ros_common.capacities (id);
ALTER TABLE ros_common.capacities ADD CONSTRAINT uk_capacities UNIQUE (unit, value);
SELECT setval('ros_common.capacities_ID_seq', (SELECT COALESCE(MAX(id), 1) FROM ros_common.capacities));