---
output: html_fragment
---

```{r echo=FALSE, results='asis'}
cat(sprintf(
  "## Table %s {#%s}\n",
  db_table$table(),
  paste0(db_table$schema(), "_", db_table$table())
))
```
#### Description

`r ifelse(is.na(db_table$table_comment()), '<p class="error">Not filled</p>', paste0('*', db_table$table_comment(), '*'))`

#### Definition {.tabset}

##### Columns

```{r}
db_table_columns <- db_table$columns()
out_table_columns(db_table_columns)
db_table_dependencies <- db_table$dependencies(file_location,
                                               db_metadata$is_column_code_list_function(),
                                               db_metadata$is_column_registry_function(),
                                               db_metadata$is_column_data_function())
with_depedencies <- nrow(db_table_dependencies) > 0
```
##### Dependencies {.tabset}

`r if (!with_depedencies) { "NO DATA" }`
```{r}
if (with_depedencies) {
  out_table_dependencies(db_table_dependencies)
}
```
##### Usages {.tabset}

NO DATA